import { useState } from 'react';
import { Link } from 'react-router-dom';
import { addMonths, format, parseISO } from 'date-fns';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, CalendarDays, ChartNoAxesCombined, Sparkles, TrendingUp, Wallet, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { toast } from 'sonner';
import { analyticsApi } from '../api/analytics';
import { useApp } from '../lib/context';
import { compact, dateLabel, money, monthLabel, percent } from '../lib/format';
import { Avatar, CardTitle, CategoryIcon, Delta, Empty, ErrorState, Loading, MonthPicker, PageHeader, Progress } from '../components/common';
import { Button } from '../components/ui/button';
import { chartTooltip } from './dashboard';
export function Analytics() {
  const { month, users } = useApp(); const [range, setRange] = useState('3'); const [customFrom, setCustomFrom] = useState(() => format(addMonths(parseISO(month + '-01'), -2), 'yyyy-MM')); const [customTo, setCustomTo] = useState(month); const [category, setCategory] = useState<string>('');
  const from = range === 'custom' ? customFrom : format(addMonths(parseISO(month + '-01'), 1 - Number(range)), 'yyyy-MM'); const to = range === 'custom' ? customTo : month;
  const summary = useQuery({ queryKey: ['summary', month], queryFn: () => analyticsApi.summary(month) }); const trends = useQuery({ queryKey: ['trends', from, to], queryFn: () => analyticsApi.trends(from, to), enabled: from <= to });
  const report = useMutation({ mutationFn: () => analyticsApi.report(month), onError: e => toast.error(e.message) });
  const s = summary.data; const weekdayTotals = Array.from({ length: 7 }, (_, i) => ({ day: i, value: s?.daily.filter(d => parseISO(d.date).getDay() === i).reduce((sum, d) => sum + d.totalCents, 0) ?? 0 })); const busiest = weekdayTotals.sort((a, b) => b.value - a.value)[0];
  const series = trends.data?.months.map(m => ({ ...m, ...m.byCategory, label: monthLabel(m.month, true) }));
  return <><PageHeader eyebrow="MIRAR PARA ENTENDER" title="Los números cuentan una historia." description="Encuentra patrones, compara tus meses y decide con más claridad." action={<MonthPicker/>}/>
    <div className="analytics-toolbar"><div className="segmented">{['3','6','12','custom'].map(r => <button key={r} className={range === r ? 'active' : ''} onClick={() => setRange(r)}>{r === 'custom' ? 'Personalizado' : `${r} meses`}</button>)}</div><Button variant="outline" onClick={() => report.mutate()} disabled={report.isPending}>{report.isPending ? <Loader2 size={16} className="animate-spin"/> : <Sparkles size={16}/>}Generar informe con IA</Button></div>
    {range === 'custom' && <div className="form-grid mb-5"><label className="field">Desde<input type="month" value={customFrom} onChange={e => setCustomFrom(e.target.value)}/></label><label className="field">Hasta<input type="month" min={customFrom} value={customTo} onChange={e => setCustomTo(e.target.value)}/></label>{from > to && <p className="field-error">La fecha final debe ser posterior a la inicial.</p>}</div>}
    {report.data && <section className="card ai-report"><div className="flex gap-2 items-center"><Sparkles size={18}/><strong>Una mirada a {monthLabel(month)}</strong><span className="badge badge-soft">Informe IA</span></div><div className="markdown-content"><ReactMarkdown>{report.data.markdown}</ReactMarkdown></div></section>}
    {summary.isLoading ? <Loading/> : !s ? <ErrorState error={summary.error} retry={() => summary.refetch()}/> : <><div className="three-grid mb-5"><div className="card stat-card"><span><Wallet size={18}/>Promedio diario</span><strong>{money(s.dailyAverageCents)}</strong><small>durante {monthLabel(month)}</small></div><div className="card stat-card"><span><CalendarDays size={18}/>El día con más gasto</span><strong>{s.totalCents ? ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'][busiest.day] : '—'}</strong><small>{money(busiest.value)} acumulados</small></div><div className="card stat-card"><span><TrendingUp size={18}/>Gasto promedio</span><strong>{money(s.expenseCount ? Math.round(s.totalCents / s.expenseCount) : 0)}</strong><small>por cada uno de tus {s.expenseCount} movimientos</small></div></div>
    <section className="card mb-5"><CardTitle title="El panorama completo" description="Evolución mensual de los gastos por categoría." action={<select aria-label="Ver evolución de categoría" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas las categorías</option>{trends.data?.categories.map(c => <option key={c.categoryId} value={String(c.categoryId)}>{c.name}</option>)}</select>}/>{trends.isLoading ? <Loading rows={3}/> : trends.isError ? <ErrorState error={trends.error} retry={() => trends.refetch()}/> : <div className="analytics-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={series} margin={{ top: 15, right: 20, left: 0, bottom: 5 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4"/><XAxis dataKey="label" tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} width={78} axisLine={false} tickLine={false}/><Tooltip {...chartTooltip} formatter={(v, name) => [money(Number(v)), name]}/>{trends.data?.categories.filter(c => !category || String(c.categoryId) === category).map(c => <Bar isAnimationActive={false} key={c.categoryId} dataKey={String(c.categoryId)} name={c.name} fill={c.color} stackId="spending" maxBarSize={80} onClick={() => setCategory(String(c.categoryId))} cursor="pointer"/>)}{!category && <Line isAnimationActive={false} dataKey="totalCents" name="Total" type="monotone" stroke="var(--primary)" strokeWidth={2} dot={{ r: 4 }}/>}</ComposedChart></ResponsiveContainer></div>}{category && <div className="card-bottom"><Button variant="ghost" onClick={() => setCategory('')}>Ver todas</Button><Button variant="outline" asChild><Link to={`/expenses?categoryId=${category}`}>Ver gastos de esta categoría<ArrowUpRight size={15}/></Link></Button></div>}</section>
    <div className="two-grid"><section className="card"><CardTitle title="Qué cambió este mes" description="Comparación con el mes anterior."/><div className="table-scroll"><table><thead><tr><th>Categoría</th><th>Este mes</th><th>Anterior</th><th>Variación</th></tr></thead><tbody>{s.byCategory.map(c => <tr key={c.categoryId}><td><Link className="category-table-link" to={`/expenses?categoryId=${c.categoryId}`}><CategoryIcon category={c} small size={15}/>{c.name}</Link></td><td>{money(c.totalCents)}</td><td className="muted">{money(c.previousCents)}</td><td><Delta value={c.previousCents ? (c.totalCents / c.previousCents - 1) * 100 : null}/></td></tr>)}</tbody></table></div>{!s.byCategory.length && <Empty title="Aún no hay datos" description="Los gastos que registres darán forma a tu análisis."/>}</section>
    <div className="stack-cards"><section className="card"><CardTitle title="Lo que aporta cada uno" description="Cuánto pagó y cuánto le correspondía."/><div className="chart-legend px-6"><span><i className="legend-dot" style={{ background: '#4f7bab' }}/>Pagó</span><span><i className="legend-dot" style={{ background: '#b1becf' }}/>Le correspondía</span></div><div className="member-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={s.byMember} margin={{ left: 0, right: 15, top: 15 }}><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false} width={72} tick={{ fill: 'var(--muted-foreground)', fontSize: 10 }}/><Tooltip {...chartTooltip} formatter={(v, n) => [money(Number(v)), n]}/><Bar isAnimationActive={false} dataKey="paidCents" name="Pagó" fill="#4f7bab" radius={[4,4,0,0]} maxBarSize={35}/><Bar isAnimationActive={false} dataKey="shareCents" name="Le correspondía" fill="#b1becf" radius={[4,4,0,0]} maxBarSize={35}/></BarChart></ResponsiveContainer></div><div className="member-legend">{s.byMember.map(m => <span key={m.userId}><Avatar user={users.find(u => u.id === m.userId)} small/>{m.name}</span>)}</div></section><section className="card"><CardTitle title="Cómo pagamos" description="Distribución por medio de pago."/><div className="padded-list">{s.byPaymentMethod.filter(p => p.totalCents).map(p => <div key={p.paymentMethodId} className="payment-stat"><div><span>{p.name}</span><strong>{money(p.totalCents)}</strong></div><Progress value={s.totalCents ? p.totalCents / s.totalCents * 100 : 0} color="#808ea1"/></div>)}</div></section></div></div>
    <div className="two-grid mt-5"><section className="card"><CardTitle title="Los comercios de siempre" description="Dónde más gastó el hogar."/><div className="padded-list">{s.topMerchants.slice(0,5).map((m, i) => <Link className="rank-row" key={m.merchant} to={`/expenses?q=${encodeURIComponent(m.merchant)}`}><span className="rank-number">{String(i + 1).padStart(2,'0')}</span><div><strong>{m.merchant}</strong><small>{m.count} movimientos</small></div><b>{money(m.totalCents)}</b><span className="muted text-xs">{percent(m.totalCents / s.totalCents * 100)}</span></Link>)}</div></section><section className="card"><CardTitle title="Los gastos más grandes" description="Movimientos que hicieron la diferencia." action={<ChartNoAxesCombined size={19}/>}/><div className="padded-list">{s.largestExpenses.map(e => <Link className="rank-row" to={`/expenses?q=${encodeURIComponent(e.description)}`} key={e.id}><div><strong>{e.description}</strong><small>{dateLabel(e.date)}</small></div><b>{money(e.amountBaseCents)}</b><ArrowUpRight size={15}/></Link>)}</div></section></div></>}
  </>;
}
