import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, House, Loader2, ShieldCheck } from 'lucide-react';
import { auth } from '../api/auth';
import { USE_MOCKS } from '../api/client';
import { DemoLoginCards } from '../demo/DemoLoginCards';
import { demoApi } from '../mocks/services/demo';
import { DEMO_PASSWORD } from '../mocks/seed/users';
import { Button } from '../components/ui/button';
import { ErrorState, Loading } from '../components/common';
const loginSchema = z.object({ email: z.email('Ingresa un email válido.'), password: z.string().min(1, 'Ingresa tu contraseña.') });
const setupSchema = z.object({ householdName: z.string().min(2, 'Elige un nombre para tu hogar.'), baseCurrency: z.string(), name: z.string().min(2, 'Ingresa tu nombre.'), email: z.email('Ingresa un email válido.'), password: z.string().min(8, 'Usa al menos 8 caracteres.') });
function AuthFrame({ children }: { children: React.ReactNode }) { return <div className="auth-page"><aside className="auth-story"><Link to="/" className="brand"><span className="brand-icon"><House size={23}/></span><span>Cuentas<span>Claras</span></span></Link><div className="auth-story-content"><span className="eyebrow">MÁS HOGAR. MENOS CUENTAS.</span><h1>Compartir casa.<br/>Disfrutar la vida.<br/><em>Lo demás, claro.</em></h1><p>Un espacio para organizar los gastos, encontrar el equilibrio y cuidar lo que construyen juntos.</p><div className="auth-art"><div className="auth-house"><House size={105} strokeWidth={1}/></div><div className="auth-note"><span className="auth-check"><Check size={17}/></span><div>Las cuentas, al día.<small>La tranquilidad, en casa.</small></div></div></div></div><div className="auth-foot"><ShieldCheck size={16}/>Tus datos, en tu propio hogar.</div></aside><main className="auth-form-side">{USE_MOCKS && <span className="demo-badge auth-demo-badge">DEMO</span>}{children}<p className="auth-bottom">Cuentas Claras · Hecho para compartir</p></main></div>; }
export function Login() {
  const navigate = useNavigate(); const qc = useQueryClient(); const [show, setShow] = useState(false); const status = useQuery({ queryKey: ['auth-status'], queryFn: auth.status }); const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(loginSchema), defaultValues: { email: '', password: '' } });
  const login = useMutation({ mutationFn: auth.login, onSuccess: () => { qc.clear(); navigate('/'); } });
  if (status.data?.needsSetup) return <Navigate to="/setup" replace/>;
  return <AuthFrame><div className="auth-form"><span className="eyebrow">QUÉ BUENO TENERTE DE VUELTA</span><h1>Estás en casa.</h1><p className="muted mb-6">Ingresa para poner tus cuentas en orden.</p>{status.isError && <ErrorState error={status.error} retry={() => status.refetch()}/>}<DemoLoginCards/><details className="auth-classic"><summary>Prefiero entrar con email y contraseña</summary><form className="stack-form" onSubmit={handleSubmit(v => login.mutate(v))}><label className="field">Email<input type="email" autoComplete="email" placeholder="tu@email.com" {...register('email')}/>{errors.email && <span className="field-error">{errors.email.message}</span>}</label><label className="field">Contraseña<div className="password-input"><input type={show ? 'text' : 'password'} autoComplete="current-password" placeholder="Tu contraseña" {...register('password')}/><button type="button" aria-label={show ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setShow(!show)}>{show ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div>{errors.password && <span className="field-error">{errors.password.message}</span>}</label>{login.error && <p className="field-error" role="alert">{login.error.message}</p>}<p className="hint">Usuarios: matias@demo.test, sofia@demo.test o lucas@demo.test · Contraseña: {DEMO_PASSWORD}</p><Button disabled={login.isPending}>{login.isPending ? <Loader2 className="animate-spin" size={17}/> : <>Entrar a mi hogar<ArrowRight size={17}/></>}</Button></form></details><p className="text-sm muted mt-6">¿Necesitas una cuenta? Pídesela al administrador de tu hogar.</p></div></AuthFrame>;
}
export function Setup() {
  const [step, setStep] = useState(1); const qc = useQueryClient(); const navigate = useNavigate(); const status = useQuery({ queryKey: ['auth-status'], queryFn: auth.status }); const form = useForm({ resolver: zodResolver(setupSchema), defaultValues: { householdName: '', baseCurrency: 'UYU', name: '', email: '', password: '' } }); const setup = useMutation({ mutationFn: auth.setup, onSuccess: () => { qc.clear(); navigate('/'); } });
  if (status.isLoading) return <Loading/>; if (status.isError) return <ErrorState error={status.error} retry={() => status.refetch()}/>; if (status.data && !status.data.needsSetup) return <Navigate to="/login" replace/>;
  return <AuthFrame><div className="auth-form"><div className="setup-steps"><span className="active">1</span><i/><span className={step === 2 ? 'active' : ''}>2</span></div><span className="eyebrow">EL COMIENZO DE ALGO MÁS SIMPLE</span><h1>{step === 1 ? 'Hagamos lugar a tu hogar.' : 'Tu primera llave.'}</h1><p className="muted mb-8">{step === 1 ? 'Solo necesitamos unos detalles para empezar.' : 'Crea la cuenta del administrador. Luego podrás sumar integrantes.'}</p><form className="stack-form" onSubmit={form.handleSubmit(v => setup.mutate(v))}>{step === 1 ? <><label className="field">Nombre del hogar<input autoFocus placeholder="Casa del Parque" {...form.register('householdName')}/><span className="field-error">{form.formState.errors.householdName?.message}</span></label><label className="field">Moneda base<select {...form.register('baseCurrency')}><option value="UYU">Pesos uruguayos (UYU)</option><option value="USD">Dólares estadounidenses (USD)</option></select></label><Button type="button" onClick={async () => { if (await form.trigger(['householdName','baseCurrency'])) setStep(2); }}>Continuar<ArrowRight size={16}/></Button></> : <><label className="field">Tu nombre<input autoFocus {...form.register('name')}/><span className="field-error">{form.formState.errors.name?.message}</span></label><label className="field">Email<input type="email" autoComplete="email" {...form.register('email')}/><span className="field-error">{form.formState.errors.email?.message}</span></label><label className="field">Contraseña<input type="password" autoComplete="new-password" placeholder="Al menos 8 caracteres" {...form.register('password')}/><span className="field-error">{form.formState.errors.password?.message}</span></label>{setup.error && <p className="field-error">{setup.error.message}</p>}<Button disabled={setup.isPending}><House size={17}/>Crear mi hogar</Button><Button type="button" variant="ghost" onClick={() => setStep(1)}><ArrowLeft size={15}/>Volver</Button></>}</form>{USE_MOCKS && <div className="demo-setup-note"><strong>Estás probando el primer arranque.</strong> Así empieza un hogar recién instalado: creas el hogar y la cuenta del administrador, y después sumas a los demás.<br/><Button type="button" variant="outline" size="sm" onClick={async () => { await demoApi.reset(); qc.clear(); navigate('/login'); }}>Volver al hogar de ejemplo</Button></div>}</div></AuthFrame>;
}
