import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Check, CircleCheck, Handshake, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { balancesApi } from '../api/balances';
import type { Debt, Settlement } from '../api/types';
import { useApp } from '../lib/context';
import { amountText, dateLabel, getBaseCurrency, money, toCents, today } from '../lib/format';
import { Avatar, CardTitle, Empty, ErrorState, Loading, PageHeader } from '../components/common';
import { Button } from '../components/ui/button';
import { Confirm, Modal } from '../components/ui/dialog';
function SettlementForm({ debt, onDone }: { debt: Debt; onDone: () => void }) {
  const { users } = useApp(); const qc = useQueryClient(); const [from, setFrom] = useState(String(debt.fromUserId)); const [to, setTo] = useState(String(debt.toUserId)); const [amount, setAmount] = useState(debt.amountCents ? amountText(debt.amountCents) : ''); const [date, setDate] = useState(today()); const [note, setNote] = useState('');
  const save = useMutation({ mutationFn: () => balancesApi.settle({ fromUserId: Number(from), toUserId: Number(to), amountCents: toCents(amount), date, note: note || null }), onSuccess: () => { void qc.invalidateQueries(); toast.success('Pago registrado. Un pendiente menos.'); onDone(); }, onError: e => toast.error(e.message) });
  return <form className="stack-form" onSubmit={e => { e.preventDefault(); if (from === to || toCents(amount) <= 0 || !Number.isFinite(toCents(amount))) { toast.error('Elige dos integrantes distintos y un monto válido.'); return; } save.mutate(); }}><div className="form-grid"><label className="field">Quién paga<select value={from} onChange={e => setFrom(e.target.value)}>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="field">Quién recibe<select value={to} onChange={e => setTo(e.target.value)}>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><label className="field">Monto en {getBaseCurrency()}<input autoFocus inputMode="decimal" placeholder="12.500" value={amount} onChange={e => setAmount(e.target.value)} required/></label><label className="field">Fecha<input type="date" value={date} onChange={e => setDate(e.target.value)} required/></label><label className="field">Nota <span className="optional">opcional</span><textarea rows={2} placeholder="Transferencia, efectivo…" value={note} onChange={e => setNote(e.target.value)}/></label><p className="inline-note"><Handshake size={16}/>Este registro actualiza las cuentas; no realiza una transferencia.</p><Button disabled={save.isPending}><Check size={17}/>Registrar pago</Button></form>;
}
export function Balances() {
  const { users } = useApp(); const qc = useQueryClient(); const [debt, setDebt] = useState<Debt>(); const [deleting, setDeleting] = useState<Settlement>();
  const q = useQuery({ queryKey: ['balances'], queryFn: balancesApi.get }); const history = useQuery({ queryKey: ['settlements'], queryFn: balancesApi.settlements });
  const remove = useMutation({ mutationFn: () => balancesApi.remove(deleting!.id), onSuccess: () => { setDeleting(undefined); void qc.invalidateQueries(); toast.success('Pago eliminado y saldos actualizados'); }, onError: e => toast.error(e.message) });
  return <><PageHeader eyebrow="COMPARTIR, SIN COMPLICARSE" title="Entre nosotros, todo claro." description="Quién pagó, cuánto le tocaba y cómo ponerse al día." action={<Button disabled={users.length < 2} onClick={() => setDebt({ fromUserId: users[0].id, toUserId: users[1].id, amountCents: 0 })}><Plus size={16}/>Registrar pago</Button>}/>{q.isLoading ? <Loading/> : q.isError ? <ErrorState error={q.error} retry={() => q.refetch()}/> : <><div className="three-grid member-balances">{q.data?.members.map(m => <section className="card member-balance" key={m.userId}><div className="flex gap-3 items-center"><Avatar user={m}/><div><h2>{m.name}</h2><p className="muted text-xs">Gastos compartidos · todos los meses</p></div></div><div className="balance-breakdown"><span>Pagó<strong>{money(m.paidCents)}</strong></span><span>Le correspondía<strong>{money(m.owedCents)}</strong></span></div><div className={`net-balance ${m.netCents < 0 ? 'negative' : ''}`}><span>{m.netCents > 0 ? 'Le deben' : m.netCents < 0 ? 'Debe' : 'Está al día'}</span><strong>{money(Math.abs(m.netCents), undefined, true)}</strong></div></section>)}</div><section className="card mt-6"><CardTitle title="Menos transferencias, más simple" description="La forma más corta de dejar todas las cuentas en cero." action={<Handshake size={22}/>}/>{q.data?.debts.length ? <div className="padded-list">{q.data.debts.map((d, i) => <div className="debt-row" key={i}><div className="debt-people"><Avatar user={users.find(u => u.id === d.fromUserId)}/><strong>{users.find(u => u.id === d.fromUserId)?.name}</strong><ArrowRight size={20} className="muted"/><Avatar user={users.find(u => u.id === d.toUserId)}/><strong>{users.find(u => u.id === d.toUserId)?.name}</strong></div><strong className="debt-value">{money(d.amountCents, undefined, true)}</strong><Button size="sm" variant="outline" onClick={() => setDebt(d)}>Registrar pago<ArrowRight size={14}/></Button></div>)}</div> : <div className="balanced-empty"><CircleCheck size={36}/><h3>¡Todos al día!</h3><p>No hay cuentas pendientes entre los integrantes.</p></div>}</section></>}
    <section className="card mt-6"><CardTitle title="Pagos entre integrantes" description="El historial de las veces que se pusieron al día."/>{history.isLoading ? <Loading/> : history.isError ? <ErrorState error={history.error} retry={() => history.refetch()}/> : history.data?.length ? <div className="table-scroll"><table><thead><tr><th>Fecha</th><th>De</th><th>Para</th><th>Nota</th><th>Monto</th><th/></tr></thead><tbody>{history.data.map(s => <tr key={s.id}><td>{dateLabel(s.date, 'dd/MM/yyyy')}</td><td>{users.find(u => u.id === s.fromUserId)?.name}</td><td>{users.find(u => u.id === s.toUserId)?.name}</td><td className="muted">{s.note || '—'}</td><td>{money(s.amountCents, undefined, true)}</td><td><Button variant="ghost" size="icon" aria-label="Eliminar pago" onClick={() => setDeleting(s)}><Trash2 size={15}/></Button></td></tr>)}</tbody></table></div> : <Empty title="Todavía no hay pagos registrados" description="Cuando alguien salde una cuenta, el pago aparecerá aquí."/>}</section>
    <Modal open={!!debt} onClose={() => setDebt(undefined)} title="Registrar un pago" description="Para que las cuentas reflejen lo que ya se pagó.">{debt && <SettlementForm debt={debt} onDone={() => setDebt(undefined)}/>}</Modal><Confirm open={!!deleting} title="¿Eliminar este pago?" description="Se revertirá el pago en los saldos de ambos integrantes." onCancel={() => setDeleting(undefined)} onConfirm={() => remove.mutate()} busy={remove.isPending}/>
  </>;
}
