import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Pencil, Plus, Target, X } from 'lucide-react';
import { toast } from 'sonner';
import { getDaysInMonth, parseISO } from 'date-fns';
import { budgetsApi } from '../api/budgets';
import { useApp } from '../lib/context';
import { amountText, currentMonth, getBaseCurrency, money, monthLabel, percent, toCents, today } from '../lib/format';
import { CardTitle, CategoryIcon, Empty, ErrorState, Loading, MonthPicker, PageHeader, Progress } from '../components/common';
import { Button } from '../components/ui/button';
import { Modal } from '../components/ui/dialog';
import type { BudgetLine } from '../api/types';
function BudgetEditor({ line, onClose }: { line: BudgetLine; onClose: () => void }) { const { month } = useApp(); const [amount, setAmount] = useState(amountText(line.amountCents)); const qc = useQueryClient(); const save = useMutation({ mutationFn: () => budgetsApi.save(month, line.categoryId, toCents(amount)), onSuccess: () => { void qc.invalidateQueries(); toast.success('Presupuesto actualizado'); onClose(); }, onError: e => toast.error(e.message) }); return <form className="inline-budget-editor" onSubmit={e => { e.preventDefault(); if (toCents(amount) > 0) save.mutate(); else toast.error('Ingresa un monto mayor a cero.'); }}><span>$</span><input autoFocus aria-label="Nuevo presupuesto" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)}/><Button size="icon" type="submit" disabled={save.isPending} aria-label="Guardar presupuesto"><Check size={16}/></Button><Button type="button" size="icon" variant="ghost" onClick={onClose} aria-label="Cancelar edición"><X size={16}/></Button></form>; }
export function Budgets() {
  const { month, categories } = useApp(); const q = useQuery({ queryKey: ['budgets', month], queryFn: () => budgetsApi.list(month) }); const [editing, setEditing] = useState<number | null | undefined>(); const [adding, setAdding] = useState(false); const [newCategory, setNewCategory] = useState(''); const [newAmount, setNewAmount] = useState(''); const qc = useQueryClient();
  const save = useMutation({ mutationFn: () => budgetsApi.save(month, newCategory ? Number(newCategory) : null, toCents(newAmount)), onSuccess: () => { void qc.invalidateQueries(); setAdding(false); setNewAmount(''); toast.success('Presupuesto creado'); }, onError: e => toast.error(e.message) });
  const total = q.data?.total; const available = total ? total.amountCents - total.spentCents : 0; const days = getDaysInMonth(parseISO(month + '-01')); const elapsed = month === currentMonth() ? Number(today().slice(8)) : month < currentMonth() ? days : 0; const remaining = Math.max(0, days - elapsed);
  return <><PageHeader eyebrow="UN PLAN PARA ESTAR TRANQUILOS" title="Dale un rumbo a tu mes." description="Presupuestos flexibles que acompañan el ritmo de tu hogar." action={<><MonthPicker/><Button onClick={() => { setNewCategory(''); setAdding(true); }}><Plus size={16}/>Definir presupuesto</Button></>}/>{q.isLoading ? <Loading/> : q.isError ? <ErrorState error={q.error} retry={() => q.refetch()}/> : <><section className="budget-hero"><div className="budget-hero-main"><span className="eyebrow">PRESUPUESTO DEL HOGAR</span>{editing === null && total ? <BudgetEditor line={total} onClose={() => setEditing(undefined)}/> : <div className="flex items-center gap-3"><strong>{total ? money(total.amountCents) : 'Sin definir'}</strong><Button variant="ghost" size="icon" aria-label="Editar presupuesto total" onClick={() => total ? setEditing(null) : setAdding(true)}><Pencil size={17}/></Button></div>}<p>{total ? `Vigente desde ${monthLabel(total.effectiveFrom, true)} · se mantiene hasta que lo cambies` : 'Define cuánto quieren gastar este mes.'}</p><Progress value={total?.pct || 0} height={9} color="#b7cbe5"/><div className="flex justify-between text-sm mt-3"><span>{money(total?.spentCents || 0)} utilizados</span><strong>{percent(total?.pct || 0)}</strong></div></div><div className="budget-hero-side"><div><span>{available < 0 ? 'Por encima del presupuesto' : 'Todavía disponible'}</span><strong>{money(Math.abs(available))}</strong></div><div><span>Puedes gastar por día</span><strong>{remaining ? money(Math.max(0, Math.floor(available / remaining))) : '—'}</strong><small>{remaining ? `${remaining} días hasta fin de mes` : 'Este mes ya terminó'}</small></div></div></section>
    <div className="section-toolbar"><div><h2>Cada categoría, su espacio</h2><p className="muted text-sm mt-1">Ajusta los montos cuando lo necesites.</p></div><div className="budget-color-legend"><span><i style={{ background: 'var(--primary)' }}/>Menos del 80%</span><span><i style={{ background: 'var(--amber)' }}/>80–100%</span><span><i style={{ background: 'var(--danger)' }}/>Superado</span></div></div>
    <div className="budget-grid">{q.data?.categories.map(line => { const cat = categories.find(c => c.id === line.categoryId); return <section className="card budget-card" key={line.categoryId}><CardTitle title={cat?.name || 'Sin categoría'} action={<CategoryIcon category={cat}/>}/><div className="budget-numbers"><strong>{money(line.spentCents)}</strong><span>de {money(line.amountCents)}</span></div><Progress value={line.pct} height={7}/><div className="budget-available"><span className={line.pct > 100 ? 'text-danger' : 'muted'}>{line.pct > 100 ? `${money(line.spentCents - line.amountCents)} por encima` : `${money(line.amountCents - line.spentCents)} disponibles`}</span><strong className={line.pct > 100 ? 'text-danger' : ''}>{percent(line.pct)}</strong></div><div className="budget-edit-row">{editing === line.categoryId ? <BudgetEditor line={line} onClose={() => setEditing(undefined)}/> : <><span>Vigente desde {monthLabel(line.effectiveFrom, true)}</span><Button size="sm" variant="ghost" onClick={() => setEditing(line.categoryId)}><Pencil size={13}/>Editar</Button></>}</div></section>; })}</div>{!q.data?.categories.length && <div className="card"><Empty title="Un presupuesto a tu medida" description="Define el monto para la primera categoría y empieza a planificar." action={<Button onClick={() => setAdding(true)}>Definir presupuesto</Button>}/></div>}</>}
    <Modal open={adding} onClose={() => setAdding(false)} title="Definir presupuesto" description={`El nuevo monto se aplicará desde ${monthLabel(month)}.`}><form className="stack-form" onSubmit={e => { e.preventDefault(); if (toCents(newAmount) > 0) save.mutate(); else toast.error('Ingresa un monto mayor a cero.'); }}><label className="field">Categoría<select value={newCategory} onChange={e => setNewCategory(e.target.value)}><option value="">Total del hogar</option>{categories.filter(c => !c.archived).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Monto mensual en {getBaseCurrency()}<input inputMode="decimal" placeholder="350.000" value={newAmount} onChange={e => setNewAmount(e.target.value)} required/></label><Button disabled={save.isPending}><Target size={16}/>Guardar presupuesto</Button></form></Modal>
  </>;
}
