import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, CircleHelp, Ellipsis, Plus, ReceiptText, ScanLine, Sparkles, Target, TrendingUp, Wallet, Lightbulb } from 'lucide-react';
import { analyticsApi } from '../api/analytics';
import { expensesApi } from '../api/expenses';
import { balancesApi } from '../api/balances';
import { recurringApi } from '../api/recurring';
import { useApp } from '../lib/context';
import { compact, dateLabel, money, percent, today } from '../lib/format';
import { Avatar, AvatarStack, CardTitle, CategoryIcon, Empty, ErrorState, Loading, MonthPicker, PageHeader, Progress } from '../components/common';
import { Button } from '../components/ui/button';
import { ExpenseRow } from './expenses';
import { getDaysInMonth, parseISO } from 'date-fns';
export const chartTooltip = { contentStyle: { borderRadius: 12, border: '1px solid var(--border)', backgroundColor: 'var(--card)', color: 'var(--foreground)', fontSize: 12, boxShadow: '0 4px 24px #0000000c' }, itemStyle: { color: 'var(--foreground)' }, cursor: { stroke: 'var(--border)' } };
export function Dashboard() {
  const { month, me, users, categories, openExpense, openActions } = useApp();
  const summary = useQuery({ queryKey: ['summary', month], queryFn: () => analyticsApi.summary(month) });
  const insights = useQuery({ queryKey: ['insights', month], queryFn: () => analyticsApi.insights(month) });
  const recent = useQuery({ queryKey: ['expenses', 'recent', month], queryFn: () => expensesApi.list({ month, pageSize: 5 }) });
  const balances = useQuery({ queryKey: ['balances'], queryFn: balancesApi.get }); const recurring = useQuery({ queryKey: ['recurring'], queryFn: recurringApi.list });
  const s = summary.data;
  if (summary.isLoading) return <Loading rows={8}/>;
  if (!s) return <ErrorState error={summary.error} retry={() => summary.refetch()}/>;
  const days = getDaysInMonth(parseISO(month + '-01')); const lastDay = s.isCurrentMonth ? Number(today().slice(8)) : days; const chart = Array.from({ length: days }, (_, i) => ({ day: i + 1, real: i < lastDay ? s.daily[i]?.cumulativeCents : undefined, ideal: s.budgetCents ? s.budgetCents / days * (i + 1) : undefined }));
  const donut = s.byCategory.slice(0, 4).map(c => ({ name: c.name, value: c.totalCents, color: c.color, id: c.categoryId }));
  if (s.byCategory.length > 4) donut.push({ name: 'Otras categorías', value: s.byCategory.slice(4).reduce((a, c) => a + c.totalCents, 0), color: '#d1d6dc', id: null });
  const remaining = (s.budgetCents || 0) - s.totalCents;
  return <>
    <PageHeader eyebrow={`HOLA, ${me.name.toLocaleUpperCase('es')} ☀`} title="Un hogar. Las cuentas claras." description="Un poco de orden para disfrutar más de lo que importa." action={<><MonthPicker/><Button onClick={openActions}><Plus size={17}/>Agregar gasto</Button></>}/>
    <div className="kpi-grid">
      <article className="kpi-card kpi-primary"><div className="kpi-label">Gastado este mes <span className="kpi-icon"><Wallet size={18}/></span></div><div className="kpi-value">{money(s.totalCents)}</div><div className="kpi-bottom"><span className="kpi-pill">{s.expenseCount} gastos</span><span>entre todos, en casa</span></div><div className="decor-rings"/></article>
      <article className="kpi-card"><div className="kpi-label">Vs. mes anterior <span className="kpi-icon"><TrendingUp size={18}/></span></div><div className="kpi-value">{s.changePct === null ? '—' : `${s.changePct > 0 ? '+' : '−'}${percent(Math.abs(s.changePct))}`}<span className={`trend-icon ${s.changePct !== null && s.changePct < 0 ? 'positive' : ''}`}>{s.changePct !== null && s.changePct < 0 ? <ArrowDownRight size={22}/> : <ArrowUpRight size={22}/>}</span></div><div className="kpi-bottom muted">Mes anterior: {money(s.previousMonthTotalCents)}</div><div className="sparkline"><ResponsiveContainer width="100%" height={29}><AreaChart data={s.daily.filter((_, i) => i % 2 === 0)}><Area isAnimationActive={false} dataKey="totalCents" type="monotone" stroke="#95a2b3" fill="#95a2b320" strokeWidth={1.5}/></AreaChart></ResponsiveContainer></div></article>
      <article className="kpi-card"><div className="kpi-label">Presupuesto utilizado <span className="kpi-icon"><Target size={18}/></span></div><div className="kpi-value">{s.budgetUsedPct === null ? '—' : percent(s.budgetUsedPct)}</div><Progress value={s.budgetUsedPct || 0}/><div className="kpi-bottom muted">de {s.budgetCents ? money(s.budgetCents) : 'un presupuesto sin definir'}</div></article>
      <article className="kpi-card"><div className="kpi-label">Proyección del mes <span className="kpi-icon"><CalendarDays size={18}/></span></div><div className="kpi-value">{s.projectionCents === null ? '—' : money(s.projectionCents)}</div><div className="kpi-bottom muted"><span className="status-dot"/>Al ritmo de tus gastos actuales <span title="Estimación: gastos fijos y cuotas del mes, más el ritmo de tus gastos variables comparado con los meses anteriores."><CircleHelp size={13}/></span></div></article>
    </div>
    <div className="dashboard-main-grid">
      <section className="card chart-card"><CardTitle title="Así va tu mes" description="Tus gastos acumulados, día a día." action={<span className="badge badge-soft">{s.budgetUsedPct !== null && s.budgetUsedPct > 100 ? 'Sobre el presupuesto' : 'Cada gasto, a la vista'}</span>}/><div className="chart-legend"><span><i className="legend-dot" style={{ background: 'var(--primary)' }}/>Gasto acumulado</span><span><i className="legend-dash"/>Ritmo ideal del presupuesto</span></div><div className="cumulative-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart} margin={{ left: -10, right: 8, top: 15, bottom: 5 }}><defs><linearGradient id="expense-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#596c85" stopOpacity={0.2}/><stop offset="100%" stopColor="#596c85" stopOpacity={0.015}/></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="day" ticks={[1, 5, 10, 15, 20, 25, days]} tickLine={false} axisLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} dy={10}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 10 }} width={75}/><Tooltip {...chartTooltip} formatter={(value, name) => [money(Number(value)), name === 'real' ? 'Gasto acumulado' : 'Ritmo ideal']} labelFormatter={day => `Día ${day}`}/><Line isAnimationActive={false} dataKey="ideal" stroke="#a9b2be" strokeWidth={1.6} strokeDasharray="5 5" dot={false} activeDot={false}/><Area isAnimationActive={false} dataKey="real" type="monotone" stroke="#3f5879" strokeWidth={2.5} fill="url(#expense-gradient)" activeDot={{ r: 5, fill: '#3f5879', strokeWidth: 3, stroke: 'var(--card)' }}/></ComposedChart></ResponsiveContainer></div><div className="chart-footer"><Lightbulb size={15}/>{remaining >= 0 ? <>Todavía tienes <strong>{money(remaining)}</strong> disponibles este mes.</> : <>Superaste el presupuesto en <strong>{money(-remaining)}</strong>.</>}<Link to="/budgets">Ver presupuesto<ArrowRight size={14}/></Link></div></section>
      <section className="card category-card"><CardTitle title="¿En qué se fue?" description="Un lugar para cada gasto." action={<Link className="icon-link" to="/analytics" aria-label="Ver análisis por categoría"><Ellipsis size={20}/></Link>}/>{s.totalCents === 0 ? <Empty title="Tu gráfico empieza con un gasto" description="Registra el primero para ver el detalle."/> : <><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={donut} dataKey="value" innerRadius="72%" outerRadius="94%" paddingAngle={3} stroke="none" cornerRadius={4} startAngle={90} endAngle={-270}>{donut.map(d => <Cell key={d.name} fill={d.color}/>)}</Pie><Tooltip {...chartTooltip} formatter={value => money(Number(value))}/></PieChart></ResponsiveContainer><div className="donut-center"><span>Gasto total</span><strong>{compact(s.totalCents)}</strong><small>este mes</small></div></div><div className="category-legend">{donut.map(d => <Link key={d.name} to={d.id ? `/expenses?categoryId=${d.id}` : '/expenses'}><i className="legend-dot" style={{ backgroundColor: d.color }}/><span>{d.name}</span><strong>{percent(d.value / s.totalCents * 100)}</strong></Link>)}</div><Link className="text-link category-link" to="/analytics">Explorar categorías<ArrowRight size={14}/></Link></>}</section>
    </div>
    <div className="section-label"><span><Sparkles size={15}/>Una mano con tus cuentas</span><span>Pequeños detalles, buenas decisiones</span></div>
    <div className="insight-grid">{insights.data?.slice(0, 2).map((insight, i) => <Link className={`insight-card ${insight.severity === 'warning' ? 'insight-warning' : 'insight-info'}`} to={insight.link || '/analytics'} key={i}><span className="insight-icon">{insight.type === 'pending_receipts' ? <ScanLine size={20}/> : <Lightbulb size={20}/>}</span><div><h3>{insight.title}</h3><p>{insight.message}</p></div><ChevronRight size={18}/></Link>)}{insights.data?.length === 0 && <div className="insight-card insight-info"><Lightbulb size={20}/><div><h3>Todo está en orden</h3><p>Las novedades de tu hogar aparecerán aquí.</p></div></div>}</div>
    <div className="dashboard-bottom-grid"><section className="card recent-card"><CardTitle title="Los últimos movimientos" description="Las pequeñas y grandes cosas de cada día." action={<Link className="text-link" to="/expenses">Ver todos<ArrowRight size={14}/></Link>}/>{recent.isLoading ? <Loading/> : recent.isError ? <ErrorState error={recent.error} retry={() => recent.refetch()}/> : recent.data?.items.length ? recent.data.items.map(e => <ExpenseRow key={e.id} expense={e} compact/>) : <Empty title="El mes está por comenzar" description="Agrega tu primer gasto para verlo aquí." action={<Button onClick={() => openExpense()}>Cargar gasto</Button>}/>}</section>
      <section className="card home-balance-card"><CardTitle title="Entre nosotros" description="Compartir también es simplificar." action={<AvatarStack/>}/>{balances.data?.debts.slice(0, 2).map((d, i) => <div key={i} className="mini-debt"><Avatar user={users.find(u => u.id === d.fromUserId)} small/><div><strong>{users.find(u => u.id === d.fromUserId)?.name} <span className="muted font-normal">le debe a</span> {users.find(u => u.id === d.toUserId)?.name}</strong><span>{money(d.amountCents)}</span></div><ArrowUpRight size={17}/></div>)}{balances.data?.debts.length === 0 && <p className="muted py-4 text-sm">Todos están al día. ¡Así da gusto!</p>}<Link className="text-link" to="/balances">Ver cuentas compartidas<ArrowRight size={14}/></Link><div className="upcoming-heading"><CalendarDays size={14}/><span>LO QUE VIENE</span></div>{recurring.data?.filter(r => r.active).sort((a, b) => a.nextDate.localeCompare(b.nextDate)).slice(0, 2).map(r => <Link key={r.id} to="/recurring" className="upcoming-row"><CategoryIcon category={categories.find(c => c.id === r.categoryId)} small size={17}/><div><strong>{r.description}</strong><span>{dateLabel(r.nextDate, 'd MMM')} · {r.mode === 'auto' ? 'Automático' : 'Por confirmar'}</span></div><b>{r.amountCents ? money(r.amountCents, r.currency) : 'Variable'}</b></Link>)}</section>
    </div>
    <div className="dashboard-footnote"><span><ReceiptText size={13}/>Un hogar organizado se disfruta más.</span><span>Hecho para compartir, pensado para ti.</span></div>
  </>;
}
