import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Search, SlidersHorizontal, Download, Plus, Pencil, Trash2, Users, Sparkles, RotateCcw, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import type { Expense } from '../api/types';
import { expensesApi } from '../api/expenses';
import { useApp } from '../lib/context';
import { dateLabel, getBaseCurrency, money } from '../lib/format';
import { downloadBlob } from '../lib/utils';
import { Avatar, CategoryIcon, Empty, ErrorState, Loading, MonthPicker, PageHeader } from '../components/common';
import { Button } from '../components/ui/button';
import { Confirm } from '../components/ui/dialog';
import { ExpenseForm } from './expense-form';
export function ExpenseRow({ expense: e, compact = false, onDelete }: { expense: Expense; compact?: boolean; onDelete?: (e: Expense) => void }) {
  const { users, categories, openExpense } = useApp(); const category = categories.find(c => c.id === e.categoryId); const user = users.find(u => u.id === e.paidById); const startX = useRef(0); const [swiped, setSwiped] = useState(false);
  return <div className={`expense-row ${swiped ? 'swiped' : ''}`} onTouchStart={ev => { startX.current = ev.touches[0].clientX; }} onTouchEnd={ev => { const dx = ev.changedTouches[0].clientX - startX.current; if (Math.abs(dx) > 60) setSwiped(dx < 0); }}>
    <button className="expense-main" onClick={() => openExpense(e)} aria-label={`Editar ${e.description}`}><CategoryIcon category={category}/><span className="expense-description"><strong>{e.description}</strong><span>{e.merchant || category?.name || 'Sin categoría'}{compact && <> <i>·</i> {dateLabel(e.date, 'd MMM')}</>}</span></span></button>
    <div className="expense-badges">{e.isShared && <span className="badge badge-neutral"><Users size={11}/><span>Compartido</span></span>}{e.installment && <span className="badge badge-neutral">Cuota {e.installment.number}/{e.installment.total}</span>}{['receipt','text'].includes(e.source) && <span className="badge badge-violet"><Sparkles size={11}/>IA</span>}{e.source === 'recurring' && <span className="badge badge-neutral"><RotateCcw size={11}/>Fijo</span>}</div>
    <span className="expense-payer"><Avatar user={user} small/>{!compact && <span>{user?.name}</span>}</span><div className="expense-amount"><strong>{money(e.amountCents, e.currency, e.amountCents % 100 !== 0)}</strong>{e.currency !== getBaseCurrency() && <span className="muted text-xs">{money(e.amountBaseCents)} {getBaseCurrency()}</span>}</div>
    {onDelete && <div className="row-actions"><Button variant="ghost" size="icon" onClick={() => openExpense(e)} aria-label={`Editar ${e.description}`}><Pencil size={15}/></Button><Button variant="ghost" size="icon" className="text-danger" onClick={() => onDelete(e)} aria-label={`Eliminar ${e.description}`}><Trash2 size={15}/></Button></div>}
  </div>;
}
export function Expenses() {
  const { month, categories, users, methods, openExpense } = useApp(); const [searchParams, setSearchParams] = useSearchParams(); const [advanced, setAdvanced] = useState(false); const [page, setPage] = useState(1); const [target, setTarget] = useState<Expense>(); const [group, setGroup] = useState(false); const qc = useQueryClient();
  useEffect(() => setPage(1), [month]);
  const filters = Object.fromEntries(searchParams.entries()); const [range, setRange] = useState(!!(filters.from || filters.to));
  function filter(key: string, value: string) { const params = new URLSearchParams(searchParams); if (value) params.set(key, value); else params.delete(key); setSearchParams(params, { replace: true }); setPage(1); }
  const query = { ...filters, ...(range ? {} : { month }), page, pageSize: 20 };
  const list = useQuery({ queryKey: ['expenses', query], queryFn: () => expensesApi.list(query) });
  const remove = useMutation({ mutationFn: () => expensesApi.remove(target!.id, group), onSuccess: () => { setTarget(undefined); setGroup(false); void qc.invalidateQueries(); toast.success('Gasto eliminado'); }, onError: e => toast.error(e.message) });
  const exportCsv = useMutation({ mutationFn: () => expensesApi.export({ ...filters, ...(range ? {} : { month }) }), onSuccess: blob => { downloadBlob(blob, `cuentas-claras-${month}.csv`); toast.success('Exportación lista'); }, onError: e => toast.error(e.message) });
  const days = [...new Set(list.data?.items.map(e => e.date) ?? [])];
  return <><PageHeader eyebrow="CADA GASTO CUENTA" title="Tus gastos, en orden." description="Todo lo que entra en la vida de tu hogar, en un solo lugar." action={<><Button variant="outline" onClick={() => exportCsv.mutate()} disabled={exportCsv.isPending}><Download size={16}/><span className="hide-small">Exportar CSV</span></Button><Button onClick={() => openExpense()}><Plus size={17}/>Nuevo gasto</Button></>}/>
    <div className="card expenses-panel"><div className="expenses-toolbar"><div><p className="muted text-xs uppercase tracking-wider">Total del período</p><strong className="filter-total">{money(list.data?.sumBaseCents ?? 0)}</strong><span className="muted text-sm ml-3">{list.data?.total ?? 0} gastos</span></div><MonthPicker/></div><div className="filter-bar"><div className="search-input"><Search size={17}/><input placeholder="Buscar un gasto o comercio…" aria-label="Buscar gastos" value={filters.q || ''} onChange={e => filter('q', e.target.value)}/>{filters.q && <button aria-label="Limpiar búsqueda" onClick={() => filter('q', '')}><X size={15}/></button>}</div><select aria-label="Filtrar categoría" value={filters.categoryId || ''} onChange={e => filter('categoryId', e.target.value)}><option value="">Todas las categorías</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><Button variant={advanced ? 'secondary' : 'outline'} onClick={() => setAdvanced(!advanced)}><SlidersHorizontal size={16}/>Filtros{Object.keys(filters).length > 0 && <span className="count">{Object.keys(filters).length}</span>}</Button></div>
    {advanced && <div className="advanced-filters"><label className="field">Quién pagó<select value={filters.paidById || ''} onChange={e => filter('paidById', e.target.value)}><option value="">Todos</option>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="field">Participante<select value={filters.participantId || ''} onChange={e => filter('participantId', e.target.value)}><option value="">Todos</option>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="field">Medio de pago<select value={filters.paymentMethodId || ''} onChange={e => filter('paymentMethodId', e.target.value)}><option value="">Todos</option>{methods.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field">Origen<select value={filters.source || ''} onChange={e => filter('source', e.target.value)}><option value="">Todos</option><option value="manual">Manual</option><option value="receipt">IA · comprobante</option><option value="text">IA · texto</option><option value="recurring">Gasto fijo</option></select></label><label className="check-label"><input type="checkbox" checked={filters.shared === 'true'} onChange={e => filter('shared', e.target.checked ? 'true' : '')}/>Solo compartidos</label><label className="check-label"><input type="checkbox" checked={range} onChange={e => { setRange(e.target.checked); if (!e.target.checked) { const p = new URLSearchParams(searchParams); p.delete('from'); p.delete('to'); setSearchParams(p); } }}/>Rango personalizado</label>{range && <><label className="field">Desde<input type="date" value={filters.from || ''} onChange={e => filter('from', e.target.value)}/></label><label className="field">Hasta<input type="date" min={filters.from} value={filters.to || ''} onChange={e => filter('to', e.target.value)}/></label></>}<Button variant="ghost" onClick={() => { setSearchParams({}); setRange(false); setPage(1); }}>Limpiar filtros</Button></div>}
    {list.isLoading ? <Loading/> : list.isError ? <ErrorState error={list.error} retry={() => list.refetch()}/> : !list.data?.items.length ? <Empty title="Un poco de espacio para empezar" description="No hay gastos con estos filtros. Puedes cambiarlos o registrar el primero." action={<Button onClick={() => openExpense()}><Plus size={16}/>Cargar un gasto</Button>}/> : days.map(day => <section key={day}><div className="day-header"><h3>{dateLabel(day, "EEEE d 'de' MMMM")}</h3><span>{money(list.data!.items.filter(e => e.date === day).reduce((a, e) => a + e.amountBaseCents, 0))}</span></div>{list.data!.items.filter(e => e.date === day).map(e => <ExpenseRow key={e.id} expense={e} onDelete={e => { setTarget(e); setGroup(false); }}/>)}</section>)}
    {(list.data?.total ?? 0) > 20 && <div className="pagination"><span>Página {page} de {Math.ceil((list.data?.total ?? 0) / 20)}</span><Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16}/>Anterior</Button><Button variant="outline" size="sm" disabled={page * 20 >= (list.data?.total ?? 0)} onClick={() => setPage(page + 1)}>Siguiente<ChevronRight size={16}/></Button></div>}</div>
    <Confirm open={!!target} title={`¿Eliminar “${target?.description}”?`} description={group ? 'Se eliminarán todas las cuotas de este gasto. Esta acción no se puede deshacer.' : 'El gasto se quitará del historial y se actualizarán los balances.'} onCancel={() => setTarget(undefined)} onConfirm={() => remove.mutate()} busy={remove.isPending}>{target?.installment && <label className="check-label"><input type="checkbox" checked={group} onChange={e => setGroup(e.target.checked)}/>Eliminar todas las cuotas de este gasto</label>}</Confirm>
  </>;
}

export function ExpenseDetail() { const { id } = useParams(); const navigate = useNavigate(); const q = useQuery({ queryKey: ['expense', Number(id)], queryFn: () => expensesApi.get(Number(id)) }); return <><PageHeader title="Los detalles de tu gasto." description="Consulta el registro, revisa el reparto o actualiza sus datos."/>{q.isLoading ? <Loading/> : q.data ? <div className="card expense-detail-card"><ExpenseForm expense={q.data} onDone={() => navigate('/expenses')}/></div> : <ErrorState error={q.error} retry={() => q.refetch()}/>}</>; }
