import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Paperclip, Loader2, Users, Info } from 'lucide-react';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';
import { expensesApi } from '../api/expenses';
import { receiptsApi } from '../api/receipts';
import type { Expense, ExpenseDraft, ExpenseInput, SplitMode } from '../api/types';
import { useApp } from '../lib/context';
import { amountText, currencyOptions, currencySymbol, getBaseCurrency, money, monthLabel, referenceQuoteText, referenceRate, toCents, today } from '../lib/format';
import { allocate, calculateSplits } from '../lib/splits';
import { Avatar, CategoryIcon } from '../components/common';
import { Button } from '../components/ui/button';
import { Switch } from '../components/ui/switch';
const schema = z.object({ amount: z.string().refine(v => Number.isFinite(toCents(v)) && toCents(v) > 0, 'Ingresa un monto mayor a cero.'), currency: z.string(), exchangeRate: z.string(), description: z.string().trim().min(2, 'Escribe una descripción.'), merchant: z.string(), date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Elige una fecha.'), categoryId: z.string(), paidById: z.string().min(1), paymentMethodId: z.string(), notes: z.string(), installments: z.string() }).refine(v => v.currency === getBaseCurrency() || Number(v.exchangeRate) > 0 || referenceRate(v.currency) !== null, { path: ['exchangeRate'], message: 'Ingresa una cotización mayor a cero.' });
type Values = z.infer<typeof schema>;
// La cotización se ingresa siempre como "1 USD = X" en la otra moneda; el backend espera "moneda del gasto → moneda base".
const toRate = (quote: number, base: string) => base === 'USD' ? 1 / quote : quote;
const fromRate = (rate: number, base: string) => base === 'USD' ? 1 / rate : rate;
export const fromDraft = (d: ExpenseDraft): ExpenseInput => ({ description: d.description, merchant: d.merchant, amountCents: d.amountCents, currency: d.currency, date: d.date || today(), categoryId: d.categoryId, paymentMethodId: d.paymentMethodId, paidById: d.paidById ?? undefined, installments: d.installments, exchangeRate: d.currency === getBaseCurrency() ? 1 : undefined, notes: d.notes ?? null, split: d.split ?? null });
export const fromExpense = (e: Expense): ExpenseInput => ({ ...e, source: undefined, installments: 1, split: e.isShared ? { mode: e.splitMode || 'equal', participants: e.splits.map(s => ({ userId: s.userId, value: e.splitMode === 'exact' ? s.amountCents : s.value ?? undefined })) } : null });
export function ExpenseForm({ expense, initial, onDone, onSave, submitLabel }: { expense?: Expense; initial?: Partial<ExpenseInput>; onDone: () => void; onSave?: (input: ExpenseInput) => void; submitLabel?: string }) {
  const { users, categories, methods, me, settings } = useApp(); const base = settings.baseCurrency; const qc = useQueryClient(); const original = expense ? fromExpense(expense) : initial;
  const [shared, setShared] = useState(!!original?.split); const [mode, setMode] = useState<SplitMode>(original?.split?.mode ?? 'equal');
  const [participants, setParticipants] = useState<number[]>(original?.split?.participants.map(p => p.userId) ?? users.filter(u => u.active).map(u => u.id));
  const [values, setValues] = useState<Record<number, string>>(Object.fromEntries(original?.split?.participants.map(p => [p.userId, String(p.value !== undefined ? (original.split?.mode === 'exact' ? p.value / 100 : p.value) : 1).replace('.', ',')]) ?? []));
  const [attachment, setAttachment] = useState<number>();
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { amount: original?.amountCents ? amountText(original.amountCents) : '', currency: original?.currency ?? base, exchangeRate: original?.currency && original.currency !== base && original.exchangeRate ? String(Number(fromRate(original.exchangeRate, base).toFixed(4))) : '', description: original?.description || '', merchant: original?.merchant || '', date: original?.date || today(), categoryId: String(original?.categoryId ?? ''), paidById: String(original?.paidById ?? me.id), paymentMethodId: String(original?.paymentMethodId ?? ''), notes: original?.notes || '', installments: String(original?.installments ?? 1) } });
  const v = form.watch(); const amount = toCents(v.amount) || 0; const rate = v.currency === base ? 1 : Number(v.exchangeRate) > 0 ? toRate(Number(v.exchangeRate), base) : referenceRate(v.currency) ?? 0; const usingReference = v.currency !== base && !(Number(v.exchangeRate) > 0) && referenceRate(v.currency) !== null;
  const split: ExpenseInput['split'] = shared ? { mode, participants: participants.map(userId => ({ userId, ...(mode !== 'equal' ? { value: mode === 'exact' ? toCents(values[userId] || '0') : Number((values[userId] || '0').replace(',', '.')) } : {}) })) } : null;
  let preview: ReturnType<typeof calculateSplits> = []; let validation = ''; try { if (shared) preview = calculateSplits(amount, rate, split); } catch (e) { validation = (e as Error).message; }
  const upload = useMutation({ mutationFn: receiptsApi.upload, onSuccess: data => { setAttachment(data[0].id); toast.success('Comprobante adjuntado. Esperando el procesamiento.'); }, onError: e => toast.error(e.message) });
  const receipt = useQuery({ queryKey: ['receipt', attachment], queryFn: () => receiptsApi.get(attachment!), enabled: !!attachment, refetchInterval: q => q.state.data?.status === 'processing' ? 2000 : false });
  useEffect(() => { const d = receipt.data?.status === 'needs_review' ? receipt.data.drafts[0] : undefined; if (!d) return; const cur = form.getValues(); if (!cur.amount) form.setValue('amount', amountText(d.amountCents)); if (!cur.description) form.setValue('description', d.description); if (!cur.merchant && d.merchant) form.setValue('merchant', d.merchant); if (d.date && cur.date === today()) form.setValue('date', d.date); if (!cur.categoryId && d.categoryId) form.setValue('categoryId', String(d.categoryId)); if (!cur.paymentMethodId && d.paymentMethodId) form.setValue('paymentMethodId', String(d.paymentMethodId)); if (d.currency === 'USD') form.setValue('currency', 'USD'); toast.info('Completamos los datos leídos del comprobante. Revísalos antes de guardar.'); }, [receipt.data?.status]); // eslint-disable-line react-hooks/exhaustive-deps
  const save = useMutation({ mutationFn: async (input: ExpenseInput) => { if (onSave) { onSave(input); return; } if (expense) await expensesApi.update(expense.id, input); else if (attachment) await receiptsApi.confirm(attachment, [input]); else await expensesApi.create(input); }, onSuccess: () => { void qc.invalidateQueries(); if (!onSave) toast.success(expense ? 'Gasto actualizado' : 'Gasto guardado. Todo en orden.'); onDone(); }, onError: e => toast.error(e.message) });
  function setSplitMode(next: SplitMode) { setMode(next); const weights = participants.length ? allocate(next === 'percentage' ? 10000 : amount, participants.map(() => 1)) : []; setValues(Object.fromEntries(participants.map((id, i) => [id, next === 'shares' ? '1' : amountText(weights[i])]))); }
  const submit = form.handleSubmit(data => { if (validation) return; save.mutate({ description: data.description, merchant: data.merchant || null, amountCents: toCents(data.amount), currency: data.currency, exchangeRate: data.currency === base ? 1 : Number(data.exchangeRate) > 0 ? Number(toRate(Number(data.exchangeRate), base).toFixed(6)) : undefined, date: data.date, categoryId: data.categoryId ? Number(data.categoryId) : null, paidById: Number(data.paidById), paymentMethodId: data.paymentMethodId ? Number(data.paymentMethodId) : null, notes: data.notes || null, installments: Number(data.installments), split }); });
  return <form onSubmit={submit} className="expense-form" noValidate>
    <div className="amount-field"><label htmlFor="expense-amount">¿Cuánto gastaste?</label><div><span>{currencySymbol(v.currency)}</span><input id="expense-amount" autoFocus inputMode="decimal" placeholder="0,00" {...form.register('amount')} onBlur={() => { if (Number.isFinite(toCents(v.amount))) form.setValue('amount', amountText(toCents(v.amount))); }}/><select aria-label="Moneda" {...form.register('currency')}>{[...new Set([...currencyOptions(base), ...(original?.currency ? [original.currency] : [])])].map(c => <option key={c}>{c}</option>)}</select></div>{form.formState.errors.amount && <p className="field-error">{form.formState.errors.amount.message}</p>}</div>
    {v.currency !== base && <div className="soft-box"><label className="field">Cotización · 1 USD en {base === 'USD' ? v.currency : base}{referenceRate(v.currency) !== null && <span className="optional">opcional</span>}<input type="number" step="0.01" min="0.01" placeholder={referenceRate('USD') && base !== 'USD' ? String(referenceRate('USD')) : undefined} {...form.register('exchangeRate')}/></label><p className="text-sm muted mt-2">Equivale a {money(Math.round(amount * rate), base, true)}{usingReference && ` · con la cotización de referencia (${referenceQuoteText()}). El gasto queda guardado en ${v.currency}.`}</p>{form.formState.errors.exchangeRate && <p className="field-error">{form.formState.errors.exchangeRate.message}</p>}</div>}
    <label className="field">Descripción<input placeholder="Por ejemplo: compra de la semana" {...form.register('description')}/>{form.formState.errors.description && <span className="field-error">{form.formState.errors.description.message}</span>}</label>
    <div className="form-grid"><label className="field">Comercio <span className="optional">opcional</span><input placeholder="¿Dónde fue?" {...form.register('merchant')}/></label><label className="field">Fecha<input type="date" {...form.register('date')}/>{form.formState.errors.date && <span className="field-error">Elige una fecha válida.</span>}</label></div>
    <fieldset><legend className="field-label">Categoría</legend><div className="category-chips">{categories.filter(c => !c.archived || c.id === Number(v.categoryId)).map(c => <button type="button" key={c.id} className={`category-chip ${Number(v.categoryId) === c.id ? 'selected' : ''}`} onClick={() => form.setValue('categoryId', String(c.id))}><CategoryIcon category={c} small size={15}/>{c.name}</button>)}</div></fieldset>
    <fieldset><legend className="field-label">¿Quién pagó?</legend><div className="member-choices">{users.filter(u => u.active || u.id === Number(v.paidById)).map(u => <button type="button" key={u.id} className={Number(v.paidById) === u.id ? 'selected' : ''} onClick={() => form.setValue('paidById', String(u.id))}><Avatar user={u} small/>{u.name}{Number(v.paidById) === u.id && <Check size={14}/>}</button>)}</div></fieldset>
    <div className="form-grid"><label className="field">Medio de pago<select {...form.register('paymentMethodId')}><option value="">Sin especificar</option>{methods.filter(m => !m.archived || m.id === Number(v.paymentMethodId)).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field">Cuotas<select disabled={!!expense?.installment} {...form.register('installments')}>{Array.from({ length: 24 }, (_, i) => <option key={i} value={i + 1}>{i === 0 ? 'Un solo pago' : `${i + 1} cuotas`}</option>)}</select></label></div>
    {Number(v.installments) > 1 && <p className="inline-note"><Info size={16}/>{v.installments} cuotas de aproximadamente {money(Math.round(amount / Number(v.installments)), v.currency, true)} a partir de {monthLabel(v.date.slice(0, 7), true)}.</p>}
    {expense?.installment && <p className="inline-note">Estás editando la cuota {expense.installment.number}/{expense.installment.total}. El monto corresponde a esta cuota.</p>}
    <div className="split-box"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Users size={18}/><strong>Dividir gasto</strong></div><Switch label="Dividir gasto" checked={shared} onCheckedChange={setShared}/></div>{shared && <div className="split-content"><p className="muted text-sm">Una cuenta compartida, sin cuentas pendientes.</p><div className="member-choices">{users.filter(u => u.active || participants.includes(u.id)).map(u => <button type="button" key={u.id} className={participants.includes(u.id) ? 'selected' : ''} onClick={() => setParticipants(p => p.includes(u.id) ? p.filter(id => id !== u.id) : [...p, u.id])}><Avatar user={u} small/>{u.name}{participants.includes(u.id) && <Check size={14}/>}</button>)}</div><label className="field">Cómo dividir<select value={mode} onChange={e => setSplitMode(e.target.value as SplitMode)}><option value="equal">Partes iguales</option><option value="percentage">Porcentajes</option><option value="exact">Montos exactos</option><option value="shares">Proporciones</option></select></label>{participants.map(id => { const user = users.find(u => u.id === id); return <div key={id} className="split-row"><span className="flex gap-2 items-center"><Avatar user={user} small/>{user?.name}</span>{mode !== 'equal' && <input aria-label={`Parte de ${user?.name}`} inputMode="decimal" placeholder={mode === 'percentage' ? '%' : mode === 'shares' ? '1' : '$'} value={values[id] ?? ''} onChange={e => setValues({ ...values, [id]: e.target.value })}/>}<strong>{money(preview.find(s => s.userId === id)?.amountCents || 0, v.currency, true)}</strong></div>; })}{validation && <p className="field-error" role="alert">{validation}</p>}</div>}</div>
    <label className="field">Notas <span className="optional">opcional</span><textarea rows={2} placeholder="Algo para recordar…" {...form.register('notes')}/></label>
    {expense?.receiptId ? <Button variant="outline" asChild><Link to={`/receipts/${expense.receiptId}`} onClick={onDone}><Paperclip size={16}/>Ver comprobante</Link></Button> : !expense && !onSave && <label className="attachment-button"><Paperclip size={16}/>{upload.isPending ? 'Subiendo…' : attachment ? receipt.data?.status === 'processing' ? 'Procesando comprobante…' : 'Comprobante adjunto' : 'Adjuntar comprobante'}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="sr-only" disabled={upload.isPending || !!attachment} onChange={e => e.target.files?.length && upload.mutate(Array.from(e.target.files))}/></label>}
    {receipt.data?.status === 'failed' && <p className="inline-note"><Info size={16}/>No pudimos leer el comprobante, pero puedes completar los datos a mano: el gasto quedará asociado a él.</p>}
    <div className="form-footer"><Button type="button" variant="outline" onClick={onDone}>Cancelar</Button><Button type="submit" disabled={save.isPending || upload.isPending || (!!attachment && (!receipt.data || receipt.data.status === 'processing'))}>{save.isPending ? <Loader2 className="animate-spin" size={17}/> : <Check size={17}/>} {submitLabel || (expense ? 'Guardar cambios' : 'Guardar gasto')}</Button></div>
  </form>;
}
