import { useState } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Archive, Check, CreditCard, Download, House, KeyRound, Monitor, Moon, Pencil, Plus, RefreshCw, ShieldCheck, Sparkles, Sun, UserRound, Users } from 'lucide-react';
import { toast } from 'sonner';
import { z } from 'zod';
import { auth } from '../api/auth';
import { categoriesApi, paymentMethodsApi, settingsApi, usersApi } from '../api/settings';
import { expensesApi } from '../api/expenses';
import { USE_MOCKS } from '../api/client';
import type { Category, PaymentMethod, User } from '../api/types';
import { useApp } from '../lib/context';
import { dateLabel, money, today } from '../lib/format';
import { downloadBlob } from '../lib/utils';
import { Avatar, CardTitle, CategoryIcon, icons, PageHeader } from '../components/common';
import { Button } from '../components/ui/button';
import { Confirm, Modal } from '../components/ui/dialog';
const colors = ['#5b7ea6','#bc8c75','#8992b8','#c58b93','#b29c63','#81a6ab','#a38cbd','#cd9572'];
type ResourceKind = 'users' | 'categories' | 'methods';
type ResourceItem = User | Category | PaymentMethod;
function ResourceForm({ kind, item, onDone }: { kind: ResourceKind; item?: ResourceItem; onDone: () => void }) {
  const { users } = useApp(); const qc = useQueryClient(); const u = item as User | undefined; const c = item as Category | undefined; const p = item as PaymentMethod | undefined;
  const [name, setName] = useState(item?.name || ''); const [email, setEmail] = useState(u?.email || ''); const [password, setPassword] = useState(''); const [role, setRole] = useState(u?.role || 'member'); const [color, setColor] = useState(c?.color || '#5b7ea6'); const [icon, setIcon] = useState(c?.icon || 'ShoppingBasket'); const [type, setType] = useState(p?.type || 'debit'); const [owner, setOwner] = useState(String(p?.ownerId || ''));
  const save = useMutation({ mutationFn: async () => {
    z.string().trim().min(2, 'El nombre debe tener al menos dos caracteres.').parse(name);
    if (kind === 'users') { z.email('Ingresa un email válido.').parse(email); if (!item) z.string().min(8, 'La contraseña debe tener al menos 8 caracteres.').parse(password); const body = { name, email, role, color, ...(!item ? { password } : {}) }; return item ? usersApi.update(item.id, body) : usersApi.create(body); }
    if (kind === 'categories') { const body = { name, icon, color, archived: false }; return item ? categoriesApi.update(item.id, body) : categoriesApi.create(body); }
    const body = { name, type, ownerId: owner ? Number(owner) : null, archived: false }; return item ? paymentMethodsApi.update(item.id, body) : paymentMethodsApi.create(body);
  }, onSuccess: () => { void qc.invalidateQueries(); toast.success('Cambios guardados'); onDone(); }, onError: e => toast.error(e instanceof z.ZodError ? e.issues[0].message : e.message) });
  return <form className="stack-form" onSubmit={e => { e.preventDefault(); save.mutate(); }}><label className="field">Nombre<input autoFocus value={name} onChange={e => setName(e.target.value)} required minLength={2}/></label>{kind === 'users' && <><label className="field">Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label>{!item && <label className="field">Contraseña inicial<input type="password" autoComplete="new-password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required/></label>}<label className="field">Rol<select value={role} onChange={e => setRole(e.target.value as User['role'])}><option value="member">Miembro</option><option value="admin">Administrador</option></select></label></>}{kind !== 'methods' && <fieldset><legend className="field-label">Color {kind === 'users' ? 'del avatar' : 'de categoría'}</legend><div className="color-choices">{colors.map(clr => <button key={clr} type="button" aria-label={`Color ${clr}`} aria-pressed={color === clr} style={{ background: clr }} onClick={() => setColor(clr)}>{color === clr && <Check size={17}/>}</button>)}<input aria-label="Color personalizado" type="color" value={color} onChange={e => setColor(e.target.value)}/></div></fieldset>}{kind === 'categories' && <fieldset><legend className="field-label">Ícono</legend><div className="icon-choices">{Object.entries(icons).map(([key, Icon]) => <button key={key} type="button" aria-label={key} className={icon === key ? 'selected' : ''} onClick={() => setIcon(key)}><Icon size={22}/></button>)}</div></fieldset>}{kind === 'methods' && <><label className="field">Tipo<select value={type} onChange={e => setType(e.target.value as PaymentMethod['type'])}><option value="cash">Efectivo</option><option value="debit">Débito</option><option value="credit">Crédito</option><option value="transfer">Transferencia</option><option value="wallet">Billetera virtual</option><option value="other">Otro</option></select></label><label className="field">Titular<select value={owner} onChange={e => setOwner(e.target.value)}><option value="">Compartido / sin titular</option>{users.filter(u => u.active).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label></>}<Button disabled={save.isPending}><Check size={16}/>Guardar {kind === 'users' ? 'integrante' : kind === 'categories' ? 'categoría' : 'medio de pago'}</Button></form>;
}
function UsdRateCard() {
  const { settings } = useApp(); const qc = useQueryClient(); const quoted = settings.quotedCurrency ?? (settings.baseCurrency === 'USD' ? 'UYU' : settings.baseCurrency); const [value, setValue] = useState(settings.usdRateSource === 'manual' && settings.usdRate ? String(settings.usdRate).replace('.', ',') : '');
  const save = useMutation({ mutationFn: (usdRate: number | null) => settingsApi.update({ usdRate }), onSuccess: (_, usdRate) => { void qc.invalidateQueries(); if (usdRate === null) setValue(''); toast.success(usdRate === null ? 'Se usará la cotización automática' : 'Cotización guardada'); }, onError: e => toast.error(e.message) });
  const refresh = useMutation({ mutationFn: settingsApi.refreshUsdRate, onSuccess: () => { void qc.invalidateQueries(); }, onError: e => toast.error(e.message) });
  const parsed = Number(value.trim().replace(',', '.'));
  return <section className="card mt-5"><CardTitle title="Cotización del dólar" description={`Convierte a ${settings.baseCurrency} los gastos en otra moneda cuando no indicas la cotización. El gasto queda guardado en su moneda original.`}/><form className="stack-form p-6 pt-0" onSubmit={e => { e.preventDefault(); if (parsed > 0) save.mutate(parsed); else toast.error('Ingresa una cotización mayor a cero.'); }}><div className="soft-box"><strong>{settings.usdRate ? `1 USD = ${money(Math.round(settings.usdRate * 100), quoted, true)}` : 'Todavía no hay cotización de referencia'}</strong><p className="text-sm muted mt-1">{settings.usdRateSource === 'manual' ? 'Fijada a mano.' : settings.usdRate ? 'Automática: se actualiza todos los días desde una fuente pública (cotización de mercado).' : 'Se obtiene automáticamente al iniciar el servidor si tiene conexión a internet, o puedes fijarla a mano.'}{settings.usdRateUpdatedAt && ` Última actualización: ${dateLabel(settings.usdRateUpdatedAt, "d 'de' MMMM, HH:mm")}.`}</p></div><label className="field">Fijar a mano · 1 USD en {quoted}<input inputMode="decimal" placeholder={settings.usdRate ? String(settings.usdRate).replace('.', ',') : '40,00'} value={value} onChange={e => setValue(e.target.value)}/></label><div className="flex gap-2 flex-wrap"><Button disabled={save.isPending || !value.trim()}>Guardar cotización</Button>{settings.usdRateSource === 'manual' ? <Button type="button" variant="outline" disabled={save.isPending} onClick={() => save.mutate(null)}>Volver a la automática</Button> : <Button type="button" variant="ghost" disabled={refresh.isPending} onClick={() => refresh.mutate()}><RefreshCw size={15} className={refresh.isPending ? 'animate-spin' : ''}/>Actualizar ahora</Button>}</div></form></section>;
}
export function SettingsPage() {
  const { me, settings, users, categories, methods, theme, setTheme } = useApp(); const qc = useQueryClient(); const [name, setName] = useState(me.name); const [color, setColor] = useState(me.color); const [household, setHousehold] = useState(settings.householdName); const [currency, setCurrency] = useState(settings.baseCurrency); const [password, setPassword] = useState({ currentPassword: '', newPassword: '' }); const [editor, setEditor] = useState<{ kind: ResourceKind; item?: ResourceItem }>(); const [target, setTarget] = useState<{ kind: ResourceKind; item: ResourceItem }>(); const [reset, setReset] = useState<User>(); const [resetPass, setResetPass] = useState(''); const [exportFrom, setExportFrom] = useState(`${today().slice(0, 4)}-01-01`); const [exportTo, setExportTo] = useState(`${today().slice(0, 4)}-12-31`);
  const mutate = useMutation({ mutationFn: (fn: () => Promise<unknown>) => fn(), onSuccess: () => { void qc.invalidateQueries(); toast.success('Cambios guardados'); }, onError: e => toast.error(e.message) });
  const remove = useMutation({ mutationFn: () => (target!.kind === 'users' ? usersApi : target!.kind === 'categories' ? categoriesApi : paymentMethodsApi).remove(target!.item.id), onSuccess: () => { setTarget(undefined); void qc.invalidateQueries(); toast.success('Registro actualizado'); }, onError: e => toast.error(e.message) });
  const backup = useMutation({ mutationFn: settingsApi.backup, onSuccess: blob => downloadBlob(blob, `cuentas-claras-${today()}.json`), onError: e => toast.error(e.message) });
  const exportData = useMutation({ mutationFn: () => expensesApi.export({ from: exportFrom, to: exportTo }), onSuccess: blob => { downloadBlob(blob, 'cuentas-claras.csv'); toast.success('Datos exportados'); }, onError: e => toast.error(e.message) });
  const tabs = [{ key: 'profile', label: 'Mi perfil', icon: UserRound }, ...(me.role === 'admin' ? [{ key: 'household', label: 'Hogar', icon: House }, { key: 'users', label: 'Integrantes', icon: Users }] : []), { key: 'categories', label: 'Categorías', icon: Archive }, { key: 'methods', label: 'Medios de pago', icon: CreditCard }, { key: 'data', label: 'Datos e IA', icon: Sparkles }];
  return <><PageHeader eyebrow="A TU MANERA" title="Un hogar que se adapta a ti." description="Los pequeños ajustes que hacen que todo funcione mejor."/><Tabs.Root defaultValue="profile" className="settings-layout"><Tabs.List className="settings-tabs" aria-label="Secciones de configuración">{tabs.map(t => <Tabs.Trigger key={t.key} value={t.key}><t.icon size={17}/>{t.label}</Tabs.Trigger>)}</Tabs.List><div className="settings-content">
    <Tabs.Content value="profile"><section className="card"><CardTitle title="Tu lugar en casa" description="Así te verán los demás integrantes."/><form className="stack-form p-6" onSubmit={e => { e.preventDefault(); mutate.mutate(() => auth.update({ name, color })); }}><div className="flex items-center gap-4"><Avatar user={{ name, color }}/><div><strong>{me.email}</strong><p className="muted text-sm">{me.role === 'admin' ? 'Administrador del hogar' : 'Miembro del hogar'}</p></div></div><label className="field">Tu nombre<input value={name} onChange={e => setName(e.target.value)} required minLength={2}/></label><fieldset><legend className="field-label">Color del avatar</legend><div className="color-choices">{colors.map(c => <button key={c} type="button" aria-label={`Avatar ${c}`} aria-pressed={color === c} style={{ background: c }} onClick={() => setColor(c)}>{color === c && <Check size={16}/>}</button>)}</div></fieldset><Button className="self-start" disabled={mutate.isPending}>Guardar perfil</Button></form></section><section className="card mt-5"><CardTitle title="Que se sienta como tú" description="Elige cómo quieres ver tus cuentas."/><div className="theme-choices">{[{ key: 'light', label: 'Claro', icon: Sun }, { key: 'dark', label: 'Oscuro', icon: Moon }, { key: 'system', label: 'Sistema', icon: Monitor }].map(t => <button className={theme === t.key ? 'selected' : ''} onClick={() => setTheme(t.key)} key={t.key}><t.icon size={23}/>{t.label}</button>)}</div></section><section className="card mt-5"><CardTitle title="Cambiar contraseña" description="Usa al menos 8 caracteres."/><form className="stack-form p-6" onSubmit={e => { e.preventDefault(); mutate.mutate(async () => { await auth.password(password); setPassword({ currentPassword: '', newPassword: '' }); }); }}><label className="field">Contraseña actual<input type="password" autoComplete="current-password" required value={password.currentPassword} onChange={e => setPassword({ ...password, currentPassword: e.target.value })}/></label><label className="field">Nueva contraseña<input type="password" autoComplete="new-password" required minLength={8} value={password.newPassword} onChange={e => setPassword({ ...password, newPassword: e.target.value })}/></label><Button className="self-start" variant="outline" disabled={mutate.isPending}><KeyRound size={16}/>Actualizar contraseña</Button></form></section></Tabs.Content>
    {me.role === 'admin' && <Tabs.Content value="household"><section className="card"><CardTitle title="El hogar que comparten" description="Los datos que los reúnen."/><form className="stack-form p-6" onSubmit={e => { e.preventDefault(); mutate.mutate(() => settingsApi.update({ householdName: household, baseCurrency: currency })); }}><label className="field">Nombre del hogar<input value={household} onChange={e => setHousehold(e.target.value)} required minLength={2}/></label><label className="field">Moneda base<select value={currency} onChange={e => setCurrency(e.target.value)}><option value="UYU">Pesos uruguayos · UYU</option><option value="USD">Dólares estadounidenses · USD</option>{!['UYU', 'USD'].includes(settings.baseCurrency) && <option value={settings.baseCurrency}>{settings.baseCurrency}</option>}</select></label><Button className="self-start" disabled={mutate.isPending}>Guardar hogar</Button></form></section><UsdRateCard/></Tabs.Content>}
    {(['users','categories','methods'] as ResourceKind[]).filter(kind => kind !== 'users' || me.role === 'admin').map(kind => <Tabs.Content value={kind} key={kind}><section className="card"><CardTitle title={kind === 'users' ? 'Las personas de tu hogar' : kind === 'categories' ? 'Un lugar para cada gasto' : 'Tus medios de pago'} description={kind === 'users' ? 'Crea las cuentas de quienes comparten la casa.' : 'Personaliza, edita o archiva sin perder el historial.'} action={<Button size="sm" onClick={() => setEditor({ kind })}><Plus size={15}/>Agregar</Button>}/><div className="settings-resource-list">{(kind === 'users' ? users : kind === 'categories' ? categories : methods).map(item => { const archived = kind === 'users' ? !(item as User).active : (item as Category).archived; return <div className={`resource-row ${archived ? 'archived' : ''}`} key={item.id}>{kind === 'users' ? <Avatar user={item as User}/> : kind === 'categories' ? <CategoryIcon category={item as Category}/> : <span className="category-icon"><CreditCard size={20}/></span>}<div className="resource-name"><strong>{item.name}</strong><small>{kind === 'users' ? `${(item as User).email} · ${(item as User).role === 'admin' ? 'Admin' : 'Miembro'}` : kind === 'methods' ? users.find(u => u.id === (item as PaymentMethod).ownerId)?.name || 'Compartido' : 'Categoría del hogar'}</small></div>{archived && <span className="badge badge-neutral">{kind === 'users' ? 'Inactivo' : 'Archivada'}</span>}<div className="resource-actions">{kind === 'users' && <Button variant="ghost" size="icon" aria-label={`Restablecer contraseña de ${item.name}`} onClick={() => { setReset(item as User); setResetPass(''); }}><KeyRound size={15}/></Button>}<Button variant="ghost" size="icon" aria-label={`Editar ${item.name}`} onClick={() => setEditor({ kind, item })}><Pencil size={15}/></Button>{archived ? <Button variant="ghost" size="sm" onClick={() => mutate.mutate(() => kind === 'users' ? usersApi.update(item.id, { active: true }) : kind === 'categories' ? categoriesApi.update(item.id, { archived: false }) : paymentMethodsApi.update(item.id, { archived: false }))}>Reactivar</Button> : <Button variant="ghost" size="icon" disabled={kind === 'users' && item.id === me.id} aria-label={`Archivar ${item.name}`} onClick={() => setTarget({ kind, item })}><Archive size={15}/></Button>}</div></div>; })}</div></section></Tabs.Content>)}
    <Tabs.Content value="data"><section className="card"><CardTitle title="Tus datos siempre son tuyos" description="Descarga el historial de gastos de tu hogar en CSV."/><div className="stack-form p-6"><div className="form-grid"><label className="field">Desde<input type="date" value={exportFrom} onChange={e => setExportFrom(e.target.value)}/></label><label className="field">Hasta<input type="date" min={exportFrom} value={exportTo} onChange={e => setExportTo(e.target.value)}/></label></div><Button className="self-start" variant="outline" disabled={exportData.isPending || exportTo < exportFrom} onClick={() => exportData.mutate()}><Download size={16}/>Exportar gastos en CSV</Button></div></section>{me.role === 'admin' && <section className="card mt-5"><CardTitle title="Una copia de seguridad" description="El servidor guarda un backup diario de los últimos 14 días. También puedes descargar uno ahora."/><div className="p-6 pt-0"><Button variant="outline" onClick={() => backup.mutate()} disabled={backup.isPending}><Download size={16}/>Descargar backup</Button></div></section>}<section className="card mt-5"><CardTitle title="Una ayuda inteligente" description="Estado del servicio de inteligencia artificial."/><div className="p-6 pt-0"><div className="ai-status"><Sparkles size={24}/><div><strong>{USE_MOCKS ? 'IA simulada en esta demo' : settings.aiEnabled ? 'IA configurada y disponible' : 'IA sin configurar'}</strong><p>{USE_MOCKS ? 'Los comprobantes, la carga por texto y el informe mensual usan una lectura simulada. En la app real se conectan con Claude.' : settings.aiEnabled ? 'Puedes escanear comprobantes y generar informes.' : 'Configura el proveedor de IA en tu servidor para habilitar estas funciones.'}</p></div><span className="status-dot"/></div></div></section><div className="self-hosted-note"><ShieldCheck size={21}/><div><strong>Tu casa. Tu servidor. Tus datos.</strong><p>{USE_MOCKS ? 'Los datos de esta demo se guardan solo en este navegador. Puedes reiniciarlos desde el botón Demo.' : 'La información se guarda en el servidor de tu hogar.'}</p></div></div></Tabs.Content>
    </div></Tabs.Root><Modal open={!!editor} onClose={() => setEditor(undefined)} title={editor ? `${editor.item ? 'Editar' : 'Agregar'} ${editor.kind === 'users' ? 'integrante' : editor.kind === 'categories' ? 'categoría' : 'medio de pago'}` : ''}>{editor && <ResourceForm kind={editor.kind} item={editor.item} onDone={() => setEditor(undefined)}/>}</Modal><Confirm open={!!target} title={`${target?.kind === 'users' ? '¿Desactivar' : '¿Archivar'} “${target?.item.name}”?`} description="Su historial se conservará y podrás reactivarlo desde esta pantalla." label={target?.kind === 'users' ? 'Desactivar' : 'Archivar'} onCancel={() => setTarget(undefined)} onConfirm={() => remove.mutate()} busy={remove.isPending}/><Modal open={!!reset} onClose={() => setReset(undefined)} title={`Restablecer contraseña de ${reset?.name}`}><form className="stack-form" onSubmit={e => { e.preventDefault(); mutate.mutate(async () => { await usersApi.resetPassword(reset!.id, resetPass); setReset(undefined); }); }}><label className="field">Nueva contraseña<input type="password" minLength={8} required autoComplete="new-password" value={resetPass} onChange={e => setResetPass(e.target.value)}/></label><Button disabled={mutate.isPending}>Restablecer contraseña</Button></form></Modal></>;
}
