import { ArrowLeft, ArrowRight, AlertCircle, Inbox, ShoppingBasket, House, Zap, Wifi, Bus, HeartPulse, GraduationCap, Utensils, Armchair, PawPrint, Play, Ticket, Shapes, type LucideIcon, RefreshCw } from 'lucide-react';
import { addMonths, format, parseISO } from 'date-fns';
import type { ReactNode } from 'react';
import type { Category, User } from '../api/types';
import { useApp } from '../lib/context';
import { initials, monthLabel, percent } from '../lib/format';
import { Button } from './ui/button';
export const icons: Record<string, LucideIcon> = { ShoppingBasket, House, Zap, Wifi, Bus, HeartPulse, GraduationCap, Utensils, Armchair, PawPrint, Play, Ticket, Shapes };
export function CategoryIcon({ category, size = 20, small = false }: { category?: Pick<Category, 'icon' | 'color'>; size?: number; small?: boolean }) { const Icon = icons[category?.icon ?? 'Shapes'] || Shapes; return <span className={`category-icon ${small ? 'small' : ''}`} style={{ color: category?.color ?? '#9da5a7', backgroundColor: `${category?.color ?? '#9da5a7'}19` }}><Icon size={size} strokeWidth={1.7}/></span>; }
export function Avatar({ user, small = false }: { user?: Pick<User, 'name' | 'color'>; small?: boolean }) { return <span className={`avatar ${small ? 'avatar-sm' : ''}`} style={{ backgroundColor: `${user?.color ?? '#5b7ea6'}24`, color: user?.color ?? '#5b7ea6' }} title={user?.name}>{initials(user?.name ?? '?')}</span>; }
export function AvatarStack() { const { users } = useApp(); return <div className="avatar-stack">{users.filter(u => u.active).map(u => <Avatar key={u.id} user={u} small/>)}</div>; }
export function MonthPicker() { const { month, setMonth } = useApp(); return <div className="month-picker"><button aria-label="Mes anterior" onClick={() => setMonth(format(addMonths(parseISO(month + '-01'), -1), 'yyyy-MM'))}><ArrowLeft size={15}/></button><span>{monthLabel(month)}</span><button aria-label="Mes siguiente" onClick={() => setMonth(format(addMonths(parseISO(month + '-01'), 1), 'yyyy-MM'))}><ArrowRight size={15}/></button></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="page-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1><p className="page-description">{description}</p></div>{action && <div className="page-actions">{action}</div>}</div>; }
export function CardTitle({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="card-heading"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>; }
export function Progress({ value, color, height = 6 }: { value: number; color?: string; height?: number }) { return <div className="progress" role="progressbar" aria-label="Presupuesto utilizado" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100} style={{ height }}><div style={{ width: `${Math.min(100, Math.max(0, value))}%`, backgroundColor: color || (value > 100 ? 'var(--danger)' : value >= 80 ? 'var(--amber)' : 'var(--primary)') }}/></div>; }
export function Empty({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-icon"><Inbox size={30} strokeWidth={1.4}/></div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function Loading({ rows = 4 }: { rows?: number }) { return <div className="loading-state" role="status" aria-label="Cargando"><div className="skeleton h-8 w-1/3 mb-5"/>{Array.from({ length: rows }, (_, i) => <div key={i} className="skeleton h-16 mb-3"/>)}</div>; }
export function ErrorState({ error, retry }: { error?: Error | null; retry?: () => void }) { return <div className="empty-state"><AlertCircle size={30}/><h3>No pudimos cargar los datos</h3><p>{error?.message ?? 'Revisa tu conexión e inténtalo nuevamente.'}</p>{retry && <Button variant="outline" onClick={retry}><RefreshCw size={16}/>Reintentar</Button>}</div>; }
export function Delta({ value }: { value: number | null }) { return value === null ? <span className="muted">Sin mes anterior</span> : <span className={`delta ${value > 0 ? 'delta-up' : 'delta-down'}`}>{value > 0 ? '↗' : '↘'} {percent(Math.abs(value))}</span>; }
