import { lazy, Suspense, useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, ChartNoAxesCombined, ChevronDown, CircleHelp, CreditCard, Handshake, House, LayoutDashboard, LogOut, Menu, MessageSquareText, Moon, PanelLeftClose, PanelLeftOpen, PencilLine, Plus, RotateCcw, ScanLine, Settings, ShieldCheck, Sun, Target } from 'lucide-react';
import { toast } from 'sonner';
import { auth } from './api/auth';
import { categoriesApi, paymentMethodsApi, settingsApi, usersApi } from './api/settings';
import { USE_MOCKS } from './api/client';
import type { Expense, ExpenseInput } from './api/types';
import { AppContext } from './lib/context';
import { currentMonth, setBaseCurrency, setReferenceRate } from './lib/format';
import { Avatar, Empty, ErrorState, Loading } from './components/common';
import { Button } from './components/ui/button';
import { Modal } from './components/ui/dialog';
import { Dashboard } from './features/dashboard';
import { Expenses, ExpenseDetail } from './features/expenses';
import { ExpenseForm } from './features/expense-form';
import { Receipts, ReceiptReview, QuickText } from './features/receipts';
const Analytics = lazy(() => import('./features/analytics').then(m => ({ default: m.Analytics })));
import { Budgets } from './features/budgets';
import { Balances } from './features/balances';
import { RecurringPage } from './features/recurring';
const SettingsPage = lazy(() => import('./features/settings').then(m => ({ default: m.SettingsPage })));
import { Login, Setup } from './features/auth';
import { DemoPanel } from './demo/DemoPanel';
const nav = [
  { path: '/', label: 'Inicio', icon: LayoutDashboard }, { path: '/expenses', label: 'Gastos', icon: CreditCard }, { path: '/receipts', label: 'Comprobantes', icon: ScanLine }, { path: '/analytics', label: 'Análisis', icon: ChartNoAxesCombined }, { path: '/budgets', label: 'Presupuestos', icon: Target }, { path: '/balances', label: 'Cuentas compartidas', icon: Handshake }, { path: '/recurring', label: 'Gastos fijos', icon: RotateCcw },
];
function Layout() {
  const [month, setMonth] = useState(currentMonth()); const [collapsed, setCollapsed] = useState(localStorage.getItem('cc-sidebar') === 'collapsed'); const [theme, setTheme] = useState(localStorage.getItem('cc-theme') || 'system'); const [actions, setActions] = useState(false); const [more, setMore] = useState(false); const [quick, setQuick] = useState(false); const [help, setHelp] = useState(false); const [editor, setEditor] = useState<{ expense?: Expense; initial?: Partial<ExpenseInput> }>(); const location = useLocation(); const navigate = useNavigate(); const qc = useQueryClient();
  const status = useQuery({ queryKey: ['auth-status'], queryFn: auth.status });
  const resources = useQuery({ queryKey: ['resources'], queryFn: async () => { const [me, users, categories, methods, settings] = await Promise.all([auth.me(), usersApi.list(), categoriesApi.list(), paymentMethodsApi.list(), settingsApi.get()]); setBaseCurrency(settings.baseCurrency); setReferenceRate(settings.usdRate); return { me, users, categories, methods, settings }; }, enabled: status.data?.needsSetup === false, retry: false });
  useEffect(() => { const media = window.matchMedia('(prefers-color-scheme: dark)'); const apply = () => { const dark = theme === 'dark' || (theme === 'system' && media.matches); document.documentElement.classList.toggle('dark', dark); }; apply(); localStorage.setItem('cc-theme', theme); media.addEventListener('change', apply); return () => media.removeEventListener('change', apply); }, [theme]);
  useEffect(() => { setMore(false); window.scrollTo({ top: 0, behavior: 'instant' }); }, [location.pathname]);
  function collapse() { setCollapsed(!collapsed); localStorage.setItem('cc-sidebar', !collapsed ? 'collapsed' : 'expanded'); }
  async function logout() { try { await auth.logout(); qc.clear(); navigate('/login'); } catch (e) { toast.error((e as Error).message); } }
  if (status.data?.needsSetup) return <Navigate to="/setup" replace/>;
  if (status.isError) return <ErrorState error={status.error} retry={() => status.refetch()}/>;
  if (resources.isError) return <ErrorState error={resources.error} retry={() => resources.refetch()}/>;
  if (!resources.data) return <div className="app-loading"><span className="brand-icon"><House size={28}/></span><p>Todo en su lugar…</p><Loading rows={2}/></div>;
  const { me, users, settings } = resources.data; const activePage = nav.find(n => n.path === '/' ? location.pathname === '/' : location.pathname.startsWith(n.path))?.label || 'Configuración';
  return <AppContext.Provider value={{ ...resources.data, month, setMonth, openExpense: (expense, initial) => setEditor({ expense, initial }), openActions: () => setActions(true), openQuickText: () => setQuick(true), theme, setTheme }}><div className={`app-shell ${collapsed ? 'sidebar-collapsed' : ''}`}>
    <aside className="sidebar"><Link to="/" className="brand"><span className="brand-icon"><House size={22} strokeWidth={1.8}/></span><span className="brand-word">Cuentas<span>Claras</span><i/></span></Link><div className="household-selector"><span className="household-icon"><House size={18}/></span><div><small>MI HOGAR</small><strong>{settings.householdName}</strong></div><ChevronDown size={15}/></div><span className="nav-label">EL DÍA A DÍA</span><nav className="desktop-nav">{nav.map((n, i) => <NavLink key={n.path} to={n.path} end={n.path === '/'} title={collapsed ? n.label : undefined} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''} ${i === 3 ? 'nav-divider' : ''}`}><n.icon size={19} strokeWidth={1.65}/><span>{n.label}</span></NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><div className="tip-icon"><House size={22} strokeWidth={1.4}/><span className="tiny-spark">✦</span></div><strong>Más hogar.<br/>Menos cuentas.</strong><p>El equilibrio empieza con un pequeño hábito.</p></div><NavLink to="/settings" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Settings size={19}/><span>Configuración</span></NavLink><button className="nav-item" onClick={() => setHelp(true)}><CircleHelp size={19}/><span>Una mano para empezar</span></button><button className="sidebar-user" onClick={collapse} title={collapsed ? 'Expandir menú' : 'Contraer menú'}><Avatar user={me} small/><div><strong>{me.name}</strong><small>{me.role === 'admin' ? 'Administrador' : 'Miembro'}</small></div>{collapsed ? <PanelLeftOpen size={16}/> : <PanelLeftClose size={16}/>}</button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><House size={14}/><span>{settings.householdName}</span><i>/</i><strong>{activePage}</strong></div><Link to="/" className="mobile-brand"><span className="brand-icon"><House size={19}/></span><strong>Cuentas Claras</strong></Link><div className="topbar-actions"><span className="household-online"><i/>Todo queda en casa</span>{USE_MOCKS && <span className="demo-badge" title="Estás en la demo: los datos son de ejemplo y se guardan en este navegador.">DEMO</span>}<div className="topbar-divider"/><Button variant="ghost" size="icon" aria-label="Cambiar tema" onClick={() => setTheme(document.documentElement.classList.contains('dark') ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>}</Button><Button variant="ghost" size="icon" aria-label="Ver comprobantes pendientes" onClick={() => navigate('/receipts')}><Bell size={18}/></Button><DropdownMenu.Root><DropdownMenu.Trigger className="profile-trigger" aria-label="Menú de perfil"><Avatar user={me} small/><ChevronDown size={13}/></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="dropdown-content" align="end" sideOffset={8}><DropdownMenu.Label>{me.name}<small>{me.email}</small></DropdownMenu.Label><DropdownMenu.Separator/><DropdownMenu.Item onSelect={() => navigate('/settings')}><UserIcon/>Mi perfil</DropdownMenu.Item><DropdownMenu.Item onSelect={logout}><LogOut size={15}/>Cerrar sesión</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></div></header>
    <main className="main-content"><Suspense fallback={<Loading rows={5}/>}><Outlet/></Suspense></main></div>
    <nav className="bottom-nav" aria-label="Navegación principal móvil"><NavLink to="/" end><LayoutDashboard size={21}/><span>Inicio</span></NavLink><NavLink to="/expenses"><CreditCard size={21}/><span>Gastos</span></NavLink><button className="fab-wrap" onClick={() => setActions(true)} aria-label="Agregar gasto"><span className="fab"><Plus size={26}/></span></button><NavLink to="/analytics"><ChartNoAxesCombined size={21}/><span>Análisis</span></NavLink><button className={more ? 'active' : ''} onClick={() => setMore(true)}><Menu size={21}/><span>Más</span></button></nav>
    <Modal open={actions} onClose={() => setActions(false)} title="Cada gasto tiene su forma." description="Elige cómo quieres registrarlo."><div className="action-menu">{[{ title: 'Cargar gasto manual', text: 'Los detalles, a tu manera.', icon: PencilLine, action: () => setEditor({}) }, { title: 'Escanear comprobante', text: 'Una foto, una captura o un PDF.', icon: ScanLine, action: () => navigate('/receipts') }, { title: 'Carga rápida con texto', text: 'Cuéntalo. La IA lo organiza.', icon: MessageSquareText, action: () => setQuick(true) }].map(a => <button key={a.title} onClick={() => { setActions(false); a.action(); }}><span><a.icon size={23}/></span><div><strong>{a.title}</strong><small>{a.text}</small></div><Plus size={18}/></button>)}</div></Modal>
    <Modal open={more} onClose={() => setMore(false)} title={settings.householdName}><div className="more-menu">{[...nav, { path: '/settings', label: 'Configuración', icon: Settings }].map(n => <NavLink key={n.path} to={n.path} onClick={() => setMore(false)}><n.icon size={20}/>{n.label}</NavLink>)}</div><div className="more-members">{users.filter(u => u.active).map(u => <span key={u.id}><Avatar user={u} small/>{u.name}</span>)}</div></Modal>
    <Modal open={!!editor} onClose={() => setEditor(undefined)} title={editor?.expense ? 'Editar gasto' : 'Un nuevo gasto'} description="Cada detalle suma a unas cuentas más claras." wide>{editor && <ExpenseForm expense={editor.expense} initial={editor.initial} onDone={() => setEditor(undefined)}/>}</Modal>
    <Modal open={quick} onClose={() => setQuick(false)} title="Escríbelo y listo." wide>{quick && <QuickText onDone={() => setQuick(false)}/>}</Modal>
    <DemoPanel/>
    <Modal open={help} onClose={() => setHelp(false)} title="Pequeños pasos, cuentas claras."><div className="help-content"><p><PencilLine size={21}/><span><strong>1. Registra los gastos</strong>Usa el botón +, una foto o unas palabras. Revisa y confirma.</span></p><p><Target size={21}/><span><strong>2. Define un presupuesto</strong>Un monto para el hogar y uno para cada categoría.</span></p><p><Handshake size={21}/><span><strong>3. Comparte con tranquilidad</strong>Divide los gastos y registra los pagos para mantener los saldos al día.</span></p><div className="soft-box"><ShieldCheck size={18}/><p>{USE_MOCKS ? 'Estás explorando un hogar de ejemplo con gastos de julio a octubre de 2026. En la demo, “hoy” es el 18 de octubre. Desde el botón Demo puedes cambiar de usuario, reiniciar los datos o activar errores simulados.' : 'Tus datos viven en el servidor de tu hogar y tu sesión se protege con una cookie segura.'}</p></div></div></Modal>
  </div></AppContext.Provider>;
}
const UserIcon = () => <Settings size={15}/>;
export default function App() { return <Routes><Route path="/login" element={<Login/>}/><Route path="/setup" element={<Setup/>}/><Route element={<Layout/>}><Route index element={<Dashboard/>}/><Route path="expenses" element={<Expenses/>}/><Route path="expenses/:id" element={<ExpenseDetail/>}/><Route path="receipts" element={<Receipts/>}/><Route path="receipts/:id" element={<ReceiptReview/>}/><Route path="analytics" element={<Analytics/>}/><Route path="budgets" element={<Budgets/>}/><Route path="balances" element={<Balances/>}/><Route path="recurring" element={<RecurringPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="*" element={<Empty title="Por aquí no era" description="Esta página no existe. Volvamos a casa." action={<Button asChild><Link to="/">Ir al inicio</Link></Button>}/>}/></Route></Routes>; }
