import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as AlertDialog from '@radix-ui/react-alert-dialog';
import { X } from 'lucide-react';
import type { ReactNode } from 'react';
import { Button } from './button';
export function Modal({ open, onClose, title, description, children, wide = false }: { open: boolean; onClose: () => void; title: string; description?: string; children: ReactNode; wide?: boolean }) {
  return <DialogPrimitive.Root open={open} onOpenChange={o => !o && onClose()}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="modal-overlay"/><DialogPrimitive.Content className={`modal-content ${wide ? 'modal-wide' : ''}`} aria-describedby={description ? undefined : undefined}><div className="modal-header"><div><DialogPrimitive.Title>{title}</DialogPrimitive.Title><DialogPrimitive.Description className={description ? 'muted text-sm mt-1' : 'sr-only'}>{description || title}</DialogPrimitive.Description></div><DialogPrimitive.Close asChild><Button variant="ghost" size="icon" aria-label="Cerrar"><X size={20}/></Button></DialogPrimitive.Close></div><div className="modal-body">{children}</div></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;
}
export function Confirm({ open, title = '¿Eliminar este registro?', description = 'Esta acción no se puede deshacer.', onCancel, onConfirm, busy = false, label = 'Eliminar', children }: { open: boolean; title?: string; description?: string; onCancel: () => void; onConfirm: () => void; busy?: boolean; label?: string; children?: ReactNode }) { return <AlertDialog.Root open={open} onOpenChange={o => !o && onCancel()}><AlertDialog.Portal><AlertDialog.Overlay className="modal-overlay"/><AlertDialog.Content className="confirm-content"><AlertDialog.Title className="font-semibold text-xl">{title}</AlertDialog.Title><AlertDialog.Description className="muted my-4">{description}</AlertDialog.Description>{children && <div className="mb-5">{children}</div>}<div className="flex justify-end gap-2"><AlertDialog.Cancel asChild><Button variant="outline" disabled={busy}>Cancelar</Button></AlertDialog.Cancel><Button variant="destructive" onClick={onConfirm} disabled={busy}>{busy ? 'Procesando…' : label}</Button></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>; }
